// Auto-generated from docs/csp.html - Candlestick Patterns Reference Library
export interface CandlestickPatternDetail {
    id: string;
    title: string;
    bars: number;
    group: 'bullish-reversals' | 'bearish-reversals' | 'bullish-continuations' | 'bearish-continuations';
    groupName: string;
    structure: string;
    psychology: string;
    outcome: string;
    svgMarkup: string;
}

export const CANDLESTICK_PATTERNS: CandlestickPatternDetail[] = [
    {
        id: 'long-white-body',
        title: 'Long White Body (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Single tall green candle with a large body appearing after a decline.',
        psychology: 'Relentless buying pressure dominates the session from opening to close.',
        outcome: 'Strong buying pressure; may signal continuation or, when appearing after a decline, a potential bullish reversal.',
        svgMarkup: '<line x1="75" y1="20" x2="75" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="63" y="35" width="24" height="60" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'hammer',
        title: 'Hammer (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Small body near the top of the range after a decline, with a long lower shadow (>= 2x body) and minimal upper shadow.',
        psychology: 'Intraday sell-off is firmly rejected by buyers pushing price back near the session high.',
        outcome: 'Potential bullish reversal; confirmation above the hammer\'s high strengthens the signal.',
        svgMarkup: '<line x1="75" y1="35" x2="75" y2="115" stroke="#2ecc71" stroke-width="2"/> <rect x="64" y="38" width="22" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'inverted-hammer',
        title: 'Inverted Hammer (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Small body near the bottom of the range after a decline, with a long upper shadow (>= 2x body) and minimal lower shadow.',
        psychology: 'Buyers attempt an intraday counter-attack; while rejected from highs, emerging demand is demonstrated.',
        outcome: 'Early sign of potential bullish reversal; a strong bullish candle above the pattern confirms improving demand.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="64" y="88" width="22" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-belt-hold',
        title: 'Belt Hold (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Tall green candle opening at or near its low after a decline and rallying to close near its high with little to no lower shadow.',
        psychology: 'Buyers take control from the open without conceding ground, sustaining upward pressure.',
        outcome: 'Strong buying from the open may mark a bullish reversal; follow-through above the candle high strengthens the signal.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="63" y="30" width="24" height="75" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-engulfing',
        title: 'Engulfing Pattern (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'A small red body engulfed completely by a subsequent taller green body appearing after a downtrend.',
        psychology: 'A lower open attracts strong demand, overwhelming prior selling pressure.',
        outcome: 'Sellers lose control as buyers overwhelm the prior session\'s body; a move above the engulfing candle\'s high confirms the reversal.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="45" y="55" width="20" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="25" x2="95" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="83" y="35" width="24" height="53" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-harami',
        title: 'Harami (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Large red candle followed by a smaller green candle whose body is contained entirely inside Day 1\'s body.',
        psychology: 'Downward momentum stalls abruptly as sellers fail to expand the range.',
        outcome: 'Selling momentum weakens; a subsequent break above the pattern strengthens the bullish reversal signal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="86" y="60" width="18" height="20" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-harami-cross',
        title: 'Harami Cross (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a Doji whose body is contained within the boundaries of Day 1\'s body.',
        psychology: 'Selling pressure dissipates into balance and indecision following an extended decline.',
        outcome: 'Stronger form of the bullish Harami, indicating indecision after a decline; bullish follow-through is needed for confirmation.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="80" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="65" x2="104" y2="65" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'piercing-line',
        title: 'Piercing Line (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a green candle that opens below Day 1\'s low and closes above the 50% midpoint of Day 1 (but below Day 1\'s open).',
        psychology: 'An initial gap-down is rejected as buyers recover more than half of the prior session\'s losses.',
        outcome: 'Sellers lose control after a gap-down; recovery above the midpoint signals a potential bullish reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="40" x2="95" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="55" width="22" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-doji-star',
        title: 'Doji Star (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a Doji that gaps down beneath Day 1\'s body.',
        psychology: 'Sellers force a gap lower but fail to generate follow-through, leading to market balance.',
        outcome: 'Selling momentum stalls after a gap-down; a bullish confirmation candle increases the likelihood of a reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="88" x2="95" y2="115" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="100" x2="104" y2="100" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bullish-meeting-lines',
        title: 'Meeting Lines (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a green candle opening sharply lower and closing at the same price as Day 1\'s close.',
        psychology: 'Bulls counter-attack the gap-down with equal force to close level with Day 1.',
        outcome: 'Selling pressure is met by strong buying, producing matching closes; subsequent upside confirmation supports a bullish reversal.',
        svgMarkup: '<line x1="55" y1="30" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="40" width="22" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="115" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="80" width="22" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-white-soldiers',
        title: 'Three White Soldiers (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three consecutive long green candles after a decline, each opening within the prior body and closing near its high.',
        psychology: 'Consistent buying pressure dominates consecutive sessions without significant pullbacks.',
        outcome: 'Sustained buying pressure across three sessions signals a strong shift toward bullish control.',
        svgMarkup: '<line x1="40" y1="65" x2="40" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="70" width="18" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="40" x2="75" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="45" width="18" height="33" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="18" x2="110" y2="60" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="22" width="18" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'morning-star',
        title: 'Morning Star (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, a downward-gapping small body, and a long green candle closing well into Day 1\'s body (typically above its midpoint).',
        psychology: 'Selling pressure gives way to indecision, followed by decisive buyer dominance.',
        outcome: 'Selling pressure gives way to indecision and then strong buying; a close well into the first candle\'s body supports a bullish reversal.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="88" x2="75" y2="115" stroke="#2ecc71" stroke-width="2"/> <rect x="67" y="95" width="16" height="10" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="30" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="40" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'morning-doji-star',
        title: 'Morning Doji Star (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, a downward-gapping isolated Doji, and a long green candle closing deeply into Day 1\'s body.',
        psychology: 'A sharp decline transitions into acute market indecision, which buyers then resolve upward.',
        outcome: 'A Doji after a sharp decline signals strong indecision; bullish follow-through can confirm a reversal.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="90" x2="75" y2="115" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="102" x2="83" y2="102" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="30" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="40" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-abandoned-baby',
        title: 'Abandoned Baby (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, an isolated Doji gapping below both neighboring candles\' shadows, and a green candle gapping up.',
        psychology: 'An island formation occurs where selling exhausts on a gap-down, followed by an immediate upward gap.',
        outcome: 'An isolated Doji after a gap-down signals exhaustion; a gap-up reversal candle confirms a potential bullish turn.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="75" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="92" x2="75" y2="112" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="102" x2="83" y2="102" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="25" x2="110" y2="75" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="35" width="20" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-tri-star',
        title: 'Tri-Star (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three consecutive Dojis appearing after a decline, with the middle Doji gapping below the other two.',
        psychology: 'Selling momentum dissipates into extreme, sustained indecision across three sessions.',
        outcome: 'Rare sequence showing extreme indecision after a decline; upside follow-through may signal a bullish reversal.',
        svgMarkup: '<line x1="40" y1="40" x2="40" y2="70" stroke="#f1c40f" stroke-width="2"/> <line x1="32" y1="55" x2="48" y2="55" stroke="#f1c40f" stroke-width="3"/> <line x1="75" y1="75" x2="75" y2="105" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="90" x2="83" y2="90" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="40" x2="110" y2="70" stroke="#f1c40f" stroke-width="2"/> <line x1="102" y1="55" x2="118" y2="55" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bullish-breakaway',
        title: 'Breakaway (5)',
        bars: 5,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, downside gap to a red candle, three smaller declining bodies, followed by a strong green candle closing within the initial gap.',
        psychology: 'Downward momentum gradually weakens after an initial gap before buyers drive price back into the gap.',
        outcome: 'Downward momentum gradually weakens before a strong bullish candle breaks back into the gap, signaling a potential reversal.',
        svgMarkup: '<line x1="28" y1="20" x2="28" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="21" y="25" width="14" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="50" y1="65" x2="50" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="70" width="12" height="12" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="72" y1="80" x2="72" y2="98" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="83" width="12" height="11" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="94" y1="90" x2="94" y2="108" stroke="#e74c3c" stroke-width="2"/> <rect x="88" y="93" width="12" height="11" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="122" y1="45" x2="122" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="114" y="50" width="16" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-inside-up',
        title: 'Three Inside Up (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'A Bullish Harami followed by a third green candle that closes above the second candle\'s high.',
        psychology: 'Selling pressure halts within the prior candle, and follow-through buying confirms buyers are gaining control.',
        outcome: 'The Harami signals weakening selling pressure; the third candle confirms that buyers are gaining control.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="55" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="50" x2="75" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="67" y="60" width="16" height="20" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="20" x2="110" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="28" width="20" height="37" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-outside-up',
        title: 'Three Outside Up (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'A Bullish Engulfing pattern followed by a third green candle closing higher than Day 2.',
        psychology: 'Momentum shifts toward buyers during the engulfing session, with follow-through confirming demand.',
        outcome: 'The engulfing pattern shifts momentum toward buyers, and the third candle provides bullish confirmation.',
        svgMarkup: '<line x1="40" y1="50" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="32" y="55" width="16" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="30" x2="75" y2="100" stroke="#2ecc71" stroke-width="2"/> <rect x="64" y="40" width="22" height="48" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="20" width="20" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-kicking',
        title: 'Kicking (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Red Marubozu followed by a green Marubozu that gaps up above Day 1\'s open.',
        psychology: 'An immediate gap above the previous open reflects an abrupt shift in market balance.',
        outcome: 'A sharp gap in the opposite direction shows an abrupt shift in market control and can produce a strong bullish reversal.',
        svgMarkup: '<line x1="55" y1="60" x2="55" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="43" y="60" width="24" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="50" stroke="#2ecc71" stroke-width="2"/> <rect x="83" y="15" width="24" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'unique-three-rivers-bottom',
        title: 'Unique Three Rivers Bottom (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, followed by a smaller red candle within Day 1\'s body making a new low with a long lower shadow, then a small green candle whose low remains above Day 2\'s low.',
        psychology: 'A new downside extreme is rejected intraday, and subsequent stabilization indicates selling exhaustion.',
        outcome: 'A new downside extreme is rejected, followed by stabilization; a bullish third candle signals a potential bottom.',
        svgMarkup: '<line x1="40" y1="30" x2="40" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="55" x2="75" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="60" width="16" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="70" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="102" y="78" width="16" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-stars-in-the-south',
        title: 'Three Stars in the South (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three declining red candles: Day 1 has a long lower shadow; Day 2 has a smaller body and a higher low; Day 3 is a small red body contained within Day 2\'s range.',
        psychology: 'Sellers make progressively less downward progress each session, unable to force lower lows.',
        outcome: 'Successively weaker bearish candles show selling momentum fading; the pattern warns of a potential bullish reversal.',
        svgMarkup: '<line x1="40" y1="30" x2="40" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="45" x2="75" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="50" width="18" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="55" x2="110" y2="75" stroke="#e74c3c" stroke-width="2"/> <rect x="102" y="58" width="16" height="14" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'concealing-swallow',
        title: 'Concealing Swallow (4)',
        bars: 4,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Four red candles: two falling Marubozus, an inverted-hammer-like red candle gapping down, engulfed by a fourth red engulfing candle.',
        psychology: 'Intense selling reaches an extreme climax as an attempted extension fails and the final candle consumes Day 3\'s range.',
        outcome: 'Persistent selling becomes vulnerable after the third candle\'s failed downside extension; the fourth candle\'s engulfing action signals potential exhaustion and reversal.',
        svgMarkup: '<line x1="35" y1="25" x2="35" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="27" y="25" width="16" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="60" y1="50" x2="60" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="52" y="50" width="16" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="85" y1="60" x2="85" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="78" y="95" width="14" height="10" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="115" y1="45" x2="115" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="106" y="50" width="18" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-stick-sandwich',
        title: 'Stick Sandwich (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Two red candles with matching closing prices sandwiching a green candle in a downtrend.',
        psychology: 'Support is tested twice at the same price level with an interim bounce showing buying interest.',
        outcome: 'Repeated support at the matching closes suggests a possible bullish reversal; confirmation above the pattern is recommended.',
        svgMarkup: '<line x1="40" y1="30" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="35" width="18" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="25" x2="75" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="35" width="18" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="30" x2="110" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="35" width="18" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'homing-pigeon',
        title: 'Homing Pigeon (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Large red candle followed by a smaller red candle whose body is contained completely inside Day 1\'s body.',
        psychology: 'Selling momentum contracts as the second red candle fails to extend lower, reflecting seller hesitation.',
        outcome: 'Selling momentum contracts as the second bearish candle remains inside the first; bullish follow-through is needed to confirm a reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="86" y="55" width="18" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'ladder-bottom',
        title: 'Ladder Bottom (5)',
        bars: 5,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three declining red candles, a fourth candle with an upper shadow showing hesitation, followed by a decisive green candle opening above Day 4\'s body and closing strongly higher.',
        psychology: 'Downtrend momentum slows as buyers attempt an upside move on Day 4, followed by strong buying follow-through on Day 5.',
        outcome: 'Three declining candles are followed by weakening bearish momentum and then a strong bullish breakout, signaling a potential trend reversal.',
        svgMarkup: '<line x1="28" y1="20" x2="28" y2="50" stroke="#e74c3c" stroke-width="2"/> <rect x="22" y="25" width="12" height="23" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="50" y1="42" x2="50" y2="68" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="46" width="12" height="19" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="72" y1="60" x2="72" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="63" width="12" height="19" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="94" y1="62" x2="94" y2="98" stroke="#e74c3c" stroke-width="2"/> <rect x="88" y="80" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="122" y1="30" x2="122" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="114" y="35" width="16" height="43" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'matching-low',
        title: 'Matching Low (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Two consecutive red candles in a downtrend sharing approximately the same closing price, typically with little to no lower shadow.',
        psychology: 'Sellers fail to push the close beneath the prior session\'s level, establishing a potential short-term floor.',
        outcome: 'Repeated support at the same closing price suggests selling pressure is losing strength; bullish confirmation is preferred before treating it as a reversal.',
        svgMarkup: '<line x1="55" y1="30" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="45" x2="95" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="50" width="22" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'long-black-body',
        title: 'Long Black Body (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Single tall red candle with a large body appearing after an advance.',
        psychology: 'Heavy selling pressure dominates the session from open to close.',
        outcome: 'Strong selling pressure; may signal continuation or, after an advance, a potential bearish reversal.',
        svgMarkup: '<line x1="75" y1="20" x2="75" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="63" y="35" width="24" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'hanging-man',
        title: 'Hanging Man (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Small body near the top of an advance with a long lower shadow (>= 2x body) and minimal upper shadow, followed by a red confirmation candle.',
        psychology: 'Intraday sell-off reveals sudden vulnerability; buyers recover the close, but supply is active.',
        outcome: 'Late-session recovery after a sharp sell-off warns of vulnerability; a lower close confirms bearish reversal pressure.',
        svgMarkup: '<line x1="75" y1="35" x2="75" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="64" y="38" width="22" height="12" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'shooting-star',
        title: 'Shooting Star (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Small body near the bottom of the range after an advance, with a long upper shadow (>= 2x body) and minimal lower shadow.',
        psychology: 'Buyers drive price sharply higher but fail to sustain the advance, retreating into the close.',
        outcome: 'Buyers push prices sharply higher but fail to hold the advance; a break below the candle\'s low strengthens the bearish signal.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="64" y="88" width="22" height="12" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-belt-hold',
        title: 'Bearish Belt Hold (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Tall red candle opening at or near its high after an advance and falling steadily to close near its low with little to no upper shadow.',
        psychology: 'Sellers take control immediately from the open and sustain downward pressure throughout the session.',
        outcome: 'Sellers take control from the open and dominate the session; the pattern warns of a potential bearish reversal.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="63" y="25" width="24" height="75" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-engulfing',
        title: 'Bearish Engulfing (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'A small green body engulfed completely by a subsequent taller red body appearing after an advance.',
        psychology: 'An initial higher open attracts heavy supply, wiping out the prior session\'s advance.',
        outcome: 'Buyers lose control as sellers overwhelm the prior session\'s body; a break below the engulfing candle strengthens the reversal.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="45" y="55" width="20" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="25" x2="95" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="83" y="35" width="24" height="55" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-harami',
        title: 'Bearish Harami (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Large green candle followed by a smaller red candle whose body is contained entirely inside Day 1\'s body.',
        psychology: 'Buying momentum stalls as buyers fail to expand the range beyond prior levels.',
        outcome: 'Buying momentum stalls as the smaller candle remains inside the prior body; downside follow-through supports a bearish reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="86" y="55" width="18" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-harami-cross',
        title: 'Bearish Harami Cross (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a Doji nested completely within Day 1\'s body.',
        psychology: 'Strong buying momentum gives way to hesitation and equilibrium at the highs.',
        outcome: 'Strong buying momentum gives way to indecision; a bearish break after the Doji confirms the potential reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="80" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="65" x2="104" y2="65" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'dark-cloud-cover',
        title: 'Dark Cloud Cover (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a red candle opening above Day 1\'s high and closing below the midpoint of Day 1\'s green body, but above its open.',
        psychology: 'A gap-up to new highs is rejected as sellers push price below the midpoint of the prior advance.',
        outcome: 'A gap-up fails as sellers push price below the midpoint of the prior bullish candle, warning of a bearish reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="35" width="22" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="18" x2="95" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="25" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-doji-star',
        title: 'Bearish Doji Star (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a Doji that gaps above Day 1\'s body.',
        psychology: 'An opening gap-up stalls as buyers fail to generate further upward progress, resulting in balance.',
        outcome: 'A gap-up Doji shows that buying momentum has stalled; a bearish confirmation candle strengthens the reversal signal.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="55" width="22" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="42" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="28" x2="104" y2="28" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bearish-meeting-lines',
        title: 'Bearish Meeting Lines (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a red candle opening sharply higher and closing at the same price as Day 1\'s close.',
        psychology: 'An opening surge is met with selling pressure, returning price back to parity with the prior close.',
        outcome: 'The gap-up advance is rejected and both sessions close near the same level, suggesting a potential bearish reversal.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="100" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="50" width="22" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="20" width="22" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'three-black-crows',
        title: 'Three Black Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive long red candles after an advance, each opening within the prior body and closing near its low.',
        psychology: 'Sellers consistently dominate consecutive sessions, overcoming buying interest without significant pullbacks.',
        outcome: 'Three consecutive strong bearish sessions demonstrate sustained selling pressure and signal a potential trend reversal or acceleration lower.',
        svgMarkup: '<line x1="40" y1="20" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="25" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="45" x2="75" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="50" width="18" height="33" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="70" x2="110" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="75" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'evening-star',
        title: 'Evening Star (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, an upward-gapping small body, and a long red candle closing well into Day 1\'s body (generally below its midpoint).',
        psychology: 'Buying momentum pauses in hesitation before decisive selling takes control.',
        outcome: 'Buying momentum stalls, followed by decisive selling; a strong third candle supports a bearish reversal.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="50" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="42" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="22" width="16" height="10" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="35" x2="110" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="45" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'evening-doji-star',
        title: 'Evening Doji Star (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, an isolated Doji gapping above Day 1\'s body, and a long red candle closing deeply into Day 1\'s body.',
        psychology: 'Buying momentum reaches equilibrium at the top before sellers take control with a sharp decline.',
        outcome: 'A Doji at the top signals pronounced indecision after an advance; a strong bearish third candle confirms the potential reversal.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="50" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="40" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="28" x2="83" y2="28" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="35" x2="110" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="45" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-abandoned-baby',
        title: 'Bearish Abandoned Baby (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, an isolated Doji gapping above both neighboring candles\' shadows, and a red candle gapping down.',
        psychology: 'An island formation develops where buying exhausts on a gap-up, followed by an immediate gap-down.',
        outcome: 'An isolated Doji after a gap-up signals exhaustion; a gap-down bearish candle confirms the potential reversal.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="60" width="20" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="38" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="26" x2="83" y2="26" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="55" x2="110" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="60" width="20" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-tri-star',
        title: 'Bearish Tri-Star (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive Dojis appearing after an advance, with the middle Doji gapping above the other two.',
        psychology: 'Buying momentum stalls into extreme indecision across three consecutive sessions.',
        outcome: 'Three Dojis indicate extreme indecision near the top; a downside break can signal a bearish reversal.',
        svgMarkup: '<line x1="40" y1="60" x2="40" y2="90" stroke="#f1c40f" stroke-width="2"/> <line x1="32" y1="75" x2="48" y2="75" stroke="#f1c40f" stroke-width="3"/> <line x1="75" y1="25" x2="75" y2="55" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="40" x2="83" y2="40" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="60" x2="110" y2="90" stroke="#f1c40f" stroke-width="2"/> <line x1="102" y1="75" x2="118" y2="75" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bearish-breakaway',
        title: 'Bearish Breakaway (5)',
        bars: 5,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, upside gap to a green candle, three smaller advancing bodies, followed by a large red candle closing within the initial gap.',
        psychology: 'Upward momentum gradually decelerates following the initial gap before sellers drive price back into the gap.',
        outcome: 'The advance loses momentum after the gap-up sequence, and the final bearish candle signals a potential reversal.',
        svgMarkup: '<line x1="28" y1="70" x2="28" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="21" y="75" width="14" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="50" y1="45" x2="50" y2="65" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="48" width="12" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="72" y1="32" x2="72" y2="50" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="35" width="12" height="11" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="94" y1="22" x2="94" y2="40" stroke="#2ecc71" stroke-width="2"/> <rect x="88" y="25" width="12" height="11" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="122" y1="25" x2="122" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="114" y="30" width="16" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'three-inside-down',
        title: 'Three Inside Down (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'A Bearish Harami followed by a third red candle closing below Day 2\'s low.',
        psychology: 'Buying stalls inside the prior candle, and follow-through selling confirms sellers are gaining control.',
        outcome: 'The Harami signals weakening buying pressure; the third candle confirms renewed bearish momentum.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="100" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="35" width="20" height="55" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="45" x2="75" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="50" width="16" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="60" x2="110" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="65" width="20" height="37" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'three-outside-down',
        title: 'Three Outside Down (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'A Bearish Engulfing pattern followed by a third red candle closing lower than Day 2.',
        psychology: 'Sellers take control during the engulfing session, and subsequent selling provides immediate confirmation.',
        outcome: 'The engulfing candle shifts control toward sellers, while the third candle confirms continuation of the reversal.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="32" y="50" width="16" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="30" x2="75" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="64" y="38" width="22" height="48" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="75" x2="110" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="80" width="20" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-kicking',
        title: 'Bearish Kicking (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Green Marubozu followed by a red Marubozu that gaps down beneath Day 1\'s open.',
        psychology: 'An immediate downside gap below the prior open reflects an abrupt shift in market balance.',
        outcome: 'A sharp downside gap between opposing Marubozu candles signals an abrupt shift from bullish to bearish control.',
        svgMarkup: '<line x1="55" y1="15" x2="55" y2="65" stroke="#2ecc71" stroke-width="2"/> <rect x="43" y="15" width="24" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="83" y="75" width="24" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'ladder-top',
        title: 'Ladder Top (5)',
        bars: 5,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three advancing green candles, a fourth candle with an upper shadow showing hesitation, followed by a decisive red candle opening lower and closing down.',
        psychology: 'The advance begins to lose momentum on Day 4, followed by a strong bearish move on Day 5 that confirms seller control.',
        outcome: 'The advance begins to lose momentum before a strong bearish fifth candle confirms a potential top.',
        svgMarkup: '<line x1="28" y1="80" x2="28" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="22" y="82" width="12" height="23" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="50" y1="62" x2="50" y2="88" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="65" width="12" height="19" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="72" y1="45" x2="72" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="48" width="12" height="19" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="94" y1="22" x2="94" y2="58" stroke="#2ecc71" stroke-width="2"/> <rect x="88" y="35" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="122" y1="45" x2="122" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="114" y="52" width="16" height="43" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'matching-high',
        title: 'Matching High (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Two consecutive green candles in an uptrend sharing approximately the same closing price, typically opening higher with little to no upper shadow.',
        psychology: 'Buyers fail to push the close above the previous session\'s close, establishing a resistance level.',
        outcome: 'Repeated failure to close above the same level creates resistance and warns of a potential bearish reversal.',
        svgMarkup: '<line x1="55" y1="35" x2="55" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="40" width="22" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="35" x2="95" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="40" width="22" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'upside-gap-two-crows',
        title: 'Upside Gap Two Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, an upward-gapping small red body, followed by a red candle opening above Day 2\'s open and closing below Day 2\'s close while remaining above Day 1\'s close.',
        psychology: 'An upside gap fails to hold momentum; two consecutive down sessions show emerging supply above support.',
        outcome: 'Failure to sustain the gap warns of exhaustion; a subsequent break below the gap supports a bearish reversal.',
        svgMarkup: '<line x1="40" y1="40" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="45" width="20" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="42" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="20" width="16" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="44" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="18" width="18" height="24" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'identical-three-crows',
        title: 'Identical Three Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive red candles where each candle opens at or very close to the preceding candle\'s close and finishes near its low.',
        psychology: 'Persistent selling with little to no recovery between sessions reflects strong downward pressure.',
        outcome: 'Persistent selling with little recovery between sessions signals strong bearish momentum and possible continuation lower.',
        svgMarkup: '<line x1="40" y1="20" x2="40" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="25" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="50" x2="75" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="55" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="80" x2="110" y2="120" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="85" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'deliberation',
        title: 'Deliberation (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Two strong green candles followed by a third small green candle that opens higher, displaying a noticeably smaller body.',
        psychology: 'After two strong advancing sessions, buyers hesitate and upward progress contracts sharply.',
        outcome: 'After two strong bullish candles, the smaller third candle shows slowing momentum and warns of a possible stall or reversal.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="50" width="18" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="25" x2="75" y2="75" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="30" width="18" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="35" stroke="#2ecc71" stroke-width="2"/> <rect x="102" y="18" width="16" height="10" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'advance-block',
        title: 'Advance Block (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive green candles making new highs, with progressively smaller bodies and longer upper shadows.',
        psychology: 'Selling pressure intensifies near session highs, repeatedly pushing price off intraday peaks.',
        outcome: 'Repeated rejection at higher prices shows weakening buying momentum and warns of a potential bearish reversal.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="35" x2="75" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="45" width="18" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="18" x2="110" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="40" width="18" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'two-crows',
        title: 'Two Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, an upward-gapping small red candle, followed by a second red candle opening within Day 2\'s body and closing well into Day 1\'s body.',
        psychology: 'An initial upside gap is rejected, and consecutive down candles show supply overcoming demand.',
        outcome: 'The gap-up fails to hold and two bearish candles signal weakening demand; downside follow-through supports a bearish reversal.',
        svgMarkup: '<line x1="40" y1="40" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="45" width="20" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="45" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="20" width="16" height="18" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="25" x2="110" y2="70" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="28" width="18" height="32" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-separating-lines',
        title: 'Bullish Separating Lines (2)',
        bars: 2,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'In an uptrend, a red candle is followed by a green candle that opens at approximately the same opening price and closes higher.',
        psychology: 'A brief bearish counter-move is immediately repelled at the open as buyers reassert dominance.',
        outcome: 'A brief bearish counter-move fails as buyers reclaim control; upside continuation is favored.',
        svgMarkup: '<line x1="55" y1="35" x2="55" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="45" width="22" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="20" width="22" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'rising-three-methods',
        title: 'Rising Three Methods (5)',
        bars: 5,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Long green candle, followed by three small declining red candles contained within the first candle\'s range, and a final strong green candle closing above Day 1\'s high.',
        psychology: 'Orderly consolidation is absorbed within the initial advance before buyers trigger a decisive breakout.',
        outcome: 'Consolidation within the trend is resolved to the upside; signals potential bullish continuation.',
        svgMarkup: '<line x1="25" y1="25" x2="25" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="18" y="30" width="14" height="65" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="48" y1="35" x2="48" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="42" y="38" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="68" y1="45" x2="68" y2="70" stroke="#e74c3c" stroke-width="2"/> <rect x="62" y="48" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="88" y1="55" x2="88" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="82" y="58" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="115" y1="15" x2="115" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="108" y="20" width="14" height="65" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'upside-tasuki-gap',
        title: 'Upside Tasuki Gap (3)',
        bars: 3,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Green candle, followed by an upward-gapping green candle, and a red candle that closes partially into the gap without filling it completely.',
        psychology: 'A mild pullback tests the gap zone as support, where buyers step in before the gap is closed.',
        outcome: 'The pullback tests the gap as support; if the gap remains open and price resumes higher, the uptrend is likely to continue.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="18" x2="75" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="22" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="28" x2="110" y2="58" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="32" width="18" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-side-by-side-white-lines',
        title: 'Bullish Side-by-Side White Lines (3)',
        bars: 3,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Green candle followed by an upside gap to two side-by-side green candles with approximately the same opening price and similar body sizes.',
        psychology: 'Price maintains elevated levels following a gap, with buyers defending the higher price plateau across two sessions.',
        outcome: 'Two similar bullish candles hold the higher gap level, suggesting the gap is being accepted and the uptrend may continue.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="20" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="20" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-three-line-strike',
        title: 'Bullish Three Line Strike (4)',
        bars: 4,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Three consecutive green candles with higher closes, followed by a long red candle opening at or above Day 3\'s close and closing at or below Day 1\'s open.',
        psychology: 'A sharp single-session pullback rapidly unwinds three sessions of gains without establishing a new downtrend.',
        outcome: 'Despite the dramatic single-session drop, classical technical analysis treats this as a temporary resting phase favoring bullish continuation.',
        svgMarkup: '<line x1="30" y1="65" x2="30" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="23" y="70" width="14" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="55" y1="45" x2="55" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="48" y="50" width="14" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="80" y1="25" x2="80" y2="65" stroke="#2ecc71" stroke-width="2"/> <rect x="73" y="30" width="14" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="115" y1="18" x2="115" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="107" y="25" width="16" height="78" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'upside-gap-three-methods',
        title: 'Upside Gap Three Methods (3)',
        bars: 3,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Two advancing green candles separated by an upside gap, followed by a red candle that opens within the second body and closes to fill the gap.',
        psychology: 'A brief corrective pullback fills the recent gap, allowing buyers an opportunity to re-enter at previous price levels.',
        outcome: 'The gap is filled by a corrective bearish candle, but the prevailing uptrend remains intact; subsequent strength favors continuation.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="20" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="25" x2="110" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="30" width="18" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-on-neck-line',
        title: 'Bullish On Neck Line (2)',
        bars: 2,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'In an uptrend, a red candle is followed by a green candle that opens lower and closes precisely at Day 1\'s low, testing support.',
        psychology: 'A pullback tests prior support without breaking down; buyers absorb the dip and defend the neckline.',
        outcome: 'Modern uptrend continuation variant; upside follow-through above the pattern high confirms trend resumption.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="85" x2="95" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="85" width="22" height="20" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-in-neck-line',
        title: 'Bullish In Neck Line (2)',
        bars: 2,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'In an uptrend, a red candle is followed by a green candle that opens lower and closes slightly inside Day 1\'s body.',
        psychology: 'A pullback encounters buying interest that recovers slightly into the prior body, reflecting absorption of supply.',
        outcome: 'Modern uptrend continuation variant; confirmation above the pattern high supports bullish resumption.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="108" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="78" width="22" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-separating-lines',
        title: 'Bearish Separating Lines (2)',
        bars: 2,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'In a downtrend, a green candle is followed by a red candle that opens at approximately the same opening price and closes lower.',
        psychology: 'A brief counter-trend bounce is immediately repelled at the open as sellers reassert dominance.',
        outcome: 'A brief bullish counter-move fails as sellers regain control, favoring continuation of the downtrend.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="35" width="22" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="65" x2="95" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="75" width="22" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'falling-three-methods',
        title: 'Falling Three Methods (5)',
        bars: 5,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Long red candle, followed by three small advancing green candles contained within the first candle\'s range, and a final strong red candle closing below Day 1\'s low.',
        psychology: 'A minor counter-trend pause is contained entirely within the initial sell-off before sellers resume the decline.',
        outcome: 'A brief counter-trend rally remains contained within the first candle\'s range before sellers resume the decline.',
        svgMarkup: '<line x1="25" y1="15" x2="25" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="18" y="20" width="14" height="65" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="48" y1="55" x2="48" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="42" y="58" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="68" y1="45" x2="68" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="62" y="48" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="88" y1="35" x2="88" y2="60" stroke="#2ecc71" stroke-width="2"/> <rect x="82" y="38" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="115" y1="25" x2="115" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="108" y="30" width="14" height="65" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'downside-tasuki-gap',
        title: 'Downside Tasuki Gap (3)',
        bars: 3,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Red candle, followed by a downward-gapping red candle, and a green candle that closes partially into the gap without filling it completely.',
        psychology: 'A corrective rebound pauses within the gap zone, where selling interest halts further upside.',
        outcome: 'The corrective rally stalls within the gap, leaving the gap as resistance and favoring continuation lower.',
        svgMarkup: '<line x1="40" y1="18" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="22" width="18" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="65" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="70" width="18" height="28" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="60" x2="110" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="63" width="18" height="17" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-side-by-side-white-lines',
        title: 'Bearish Side-by-Side White Lines (3)',
        bars: 3,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Red candle followed by a downside gap to two side-by-side green candles with approximately the same opening price and similar body sizes.',
        psychology: 'Two consecutive positive sessions fail to challenge or close the downside gap, showing weak rebound power.',
        outcome: 'Two similar bullish candles fail to reclaim the downside gap, suggesting the downtrend remains intact.',
        svgMarkup: '<line x1="40" y1="15" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="20" width="18" height="38" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="65" x2="75" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="72" width="18" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="65" x2="110" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="72" width="18" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-three-line-strike',
        title: 'Bearish Three Line Strike (4)',
        bars: 4,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Three consecutive red candles with lower closes, followed by a long green candle opening at or below Day 3\'s close and closing at or above Day 1\'s open.',
        psychology: 'A sharp single-session rally temporarily recovers the losses of the prior three sessions without confirming a structural reversal.',
        outcome: 'A sharp counter-trend rally fails to reverse the broader decline; renewed selling below the pattern supports bearish continuation.',
        svgMarkup: '<line x1="30" y1="20" x2="30" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="23" y="25" width="14" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="55" y1="40" x2="55" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="48" y="45" width="14" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="80" y1="60" x2="80" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="73" y="65" width="14" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="115" y1="15" x2="115" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="107" y="20" width="16" height="78" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'downside-gap-three-methods',
        title: 'Downside Gap Three Methods (3)',
        bars: 3,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Two falling red candles separated by a downside gap, followed by a green candle that opens within the second body and closes to fill the gap.',
        psychology: 'A corrective rebound rallies into the recent gap area, testing resistance created by the prior sell-off.',
        outcome: 'The bullish gap-fill represents a corrective rebound; if sellers regain control afterward, the downtrend resumes.',
        svgMarkup: '<line x1="40" y1="15" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="20" width="18" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="65" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="70" width="18" height="28" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="35" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="40" width="18" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-on-neck-line',
        title: 'Bearish On Neck Line (2)',
        bars: 2,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'In a downtrend, a long red candle is followed by a smaller green candle that opens below Day 1\'s low and closes near Day 1\'s low.',
        psychology: 'A minor rebound after a gap-down fails to make meaningful progress into the prior session\'s body, stalling at the neckline.',
        outcome: 'Failure of buyers to push price into the previous candle\'s body indicates persistent weakness, favoring downtrend continuation.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="85" x2="95" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="85" width="22" height="20" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-in-neck-line',
        title: 'Bearish In Neck Line (2)',
        bars: 2,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'In a downtrend, a long red candle is followed by a smaller green candle that opens below Day 1\'s low and closes slightly inside Day 1\'s body.',
        psychology: 'Buyers attempt a rebound after a gap-down but fail to penetrate significantly into the prior session\'s range.',
        outcome: 'Weak penetration into the prior candle reflects insufficient demand to reverse the decline, favoring downtrend continuation.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="108" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="78" width="22" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
];

export interface CandlestickGroup {
    id: 'bullish-reversals' | 'bearish-reversals' | 'bullish-continuations' | 'bearish-continuations';
    title: string;
    subtitle: string;
    badgeClass: string;
}

export const CANDLESTICK_GROUPS: CandlestickGroup[] = [
    {
        id: 'bullish-reversals',
        title: 'Part I: Bullish Reversals',
        subtitle: 'Appears at the bottom of a downtrend; signals sellers are exhausted and buyers are taking control.',
        badgeClass: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/20',
    },
    {
        id: 'bearish-reversals',
        title: 'Part II: Bearish Reversals',
        subtitle: 'Appears at the peak of an uptrend; signals buyers are exhausted and distribution is underway.',
        badgeClass: 'bg-rose-500/15 text-rose-400 border border-rose-500/20',
    },
    {
        id: 'bullish-continuations',
        title: 'Part III: Bullish Continuations',
        subtitle: 'Appears during an uptrend; represents consolidation before upward resumption.',
        badgeClass: 'bg-blue-500/15 text-blue-400 border border-blue-500/20',
    },
    {
        id: 'bearish-continuations',
        title: 'Part IV: Bearish Continuations',
        subtitle: 'Appears during a downtrend; represents temporary pause or pullback before downward resumption.',
        badgeClass: 'bg-amber-500/15 text-amber-400 border border-amber-500/20',
    },
];

const norm = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const LOOKUP_MAP = new Map<string, CandlestickPatternDetail>();

for (const p of CANDLESTICK_PATTERNS) {
    LOOKUP_MAP.set(p.id, p);
    LOOKUP_MAP.set(norm(p.id), p);
    LOOKUP_MAP.set(norm(p.title), p);
    const titleWithoutBars = p.title.replace(/\s*\(\d+\)/, '');
    LOOKUP_MAP.set(norm(titleWithoutBars), p);
    // Explicit full names with prefix
    if (p.group.startsWith('bullish')) {
        LOOKUP_MAP.set('bullish' + norm(titleWithoutBars), p);
    } else if (p.group.startsWith('bearish')) {
        LOOKUP_MAP.set('bearish' + norm(titleWithoutBars), p);
    }
}

export function getCandlestickPatternDetails(
    pattern: { longName?: string; shortName?: string; sentiment?: string } | null | undefined
): CandlestickPatternDetail | null {
    if (!pattern) return null;
    if (pattern.longName) {
        const direct = LOOKUP_MAP.get(norm(pattern.longName));
        if (direct) return direct;
        if (pattern.sentiment) {
            const prefix = pattern.sentiment.toLowerCase().startsWith('bullish') ? 'bullish' : 'bearish';
            const withPrefix = LOOKUP_MAP.get(prefix + norm(pattern.longName));
            if (withPrefix) return withPrefix;
        }
        const clean = norm(pattern.longName).replace(/^bullish/, '').replace(/^bearish/, '');
        const fallback = LOOKUP_MAP.get(clean);
        if (fallback) return fallback;
    }
    return null;
}
