// Auto-generated from docs/csp.html - Candlestick Patterns Reference Library
export interface CandlestickPatternDetail {
    id: string;
    title: string;
    bars: number;
    group: 'bullish-reversals' | 'bearish-reversals' | 'bullish-continuations' | 'bearish-continuations';
    groupName: string;
    structure: string;
    psychology: string;
    outcome: string;
    svgMarkup: string;
}

export const CANDLESTICK_PATTERNS: CandlestickPatternDetail[] = [
    {
        id: 'long-white-body',
        title: 'Long White Body (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Single tall green candle with a large body appearing after a decline.',
        psychology: 'Relentless buying pressure dominates from opening to close.',
        outcome: 'Bullish breakout toward overhead resistance.',
        svgMarkup: '<line x1="75" y1="20" x2="75" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="63" y="35" width="24" height="60" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'hammer',
        title: 'Hammer (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Small body at the top of the range with a long lower shadow (>= 2x body) and minimal upper shadow.',
        psychology: 'Severe intraday sell-off rejected violently by buyers.',
        outcome: 'Bullish reversal upon a higher close next session.',
        svgMarkup: '<line x1="75" y1="35" x2="75" y2="115" stroke="#2ecc71" stroke-width="2"/> <rect x="64" y="38" width="22" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'inverted-hammer',
        title: 'Inverted Hammer (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Small body at the bottom of the range with a long upper shadow (>= 2x body) and minimal lower shadow.',
        psychology: 'Bulls stage an intraday counter-attack, showing emerging demand.',
        outcome: 'Requires bullish confirmation candle next session.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="64" y="88" width="22" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-belt-hold',
        title: 'Belt Hold (1)',
        bars: 1,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Opens on the absolute low of the day (shaved bottom) and rallies steadily to close near the high.',
        psychology: 'Bulls seize control instantly at the open without conceding ground.',
        outcome: 'Immediate floor established; upside continuation expected.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="63" y="30" width="24" height="75" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-engulfing',
        title: 'Engulfing Pattern (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Small red body engulfed completely by a tall green real body.',
        psychology: 'A lower open attracts massive demand, overwhelming supply.',
        outcome: 'High reliability upward reversal; stop placed below Day 2 low.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="45" y="55" width="20" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="25" x2="95" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="83" y="35" width="24" height="53" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-harami',
        title: 'Harami (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Large red candle followed by a smaller green candle contained entirely inside Day 1\'s body.',
        psychology: 'Downward momentum hits a sudden stop; sellers fail to expand range.',
        outcome: 'Trend deceleration; break above Day 1 midpoint confirms reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="86" y="60" width="18" height="20" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-harami-cross',
        title: 'Harami Cross (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a Doji inside the boundaries of Day 1\'s body.',
        psychology: 'Market reaches total equilibrium and indecision following intense selling.',
        outcome: 'Potent turning point; upside expansion expected.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="80" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="65" x2="104" y2="65" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'piercing-line',
        title: 'Piercing Line (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a green candle that opens below Day 1 low and closes above the 50% midpoint of Day 1.',
        psychology: 'Heavy gap-down rejected; buyers recover over half of Day 1 losses.',
        outcome: 'Institutional accumulation; upward test of resistance.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="40" x2="95" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="55" width="22" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-doji-star',
        title: 'Doji Star (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red body followed by a Doji that gaps down beneath Day 1\'s body.',
        psychology: 'Sellers force a lower opening but are completely unable to follow through.',
        outcome: 'Early alert of trend exhaustion; look for a strong green candle to confirm.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="88" x2="95" y2="115" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="100" x2="104" y2="100" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bullish-meeting-lines',
        title: 'Meeting Lines (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a green candle opening sharply lower but closing at the exact same price as Day 1\'s close.',
        psychology: 'Bulls counter-attack the gap-down with equal force to close level with Day 1.',
        outcome: 'Downward trend halted cold; upward reversal anticipated.',
        svgMarkup: '<line x1="55" y1="30" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="40" width="22" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="115" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="80" width="22" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-white-soldiers',
        title: 'Three White Soldiers (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three consecutive long green candles, each opening within the prior body and closing higher near highs.',
        psychology: 'Steady, overpowering institutional buying demolishing resistance.',
        outcome: 'Sustained bull run initiation.',
        svgMarkup: '<line x1="40" y1="65" x2="40" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="70" width="18" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="40" x2="75" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="45" width="18" height="33" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="18" x2="110" y2="60" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="22" width="18" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'morning-star',
        title: 'Morning Star (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, downward gapping small body, and a long green candle closing deeply into Day 1.',
        psychology: 'Panic capitulation shifts into indecision, then aggressive buyer dominance.',
        outcome: 'Major cyclical bottom; high-probability upward trend.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="88" x2="75" y2="115" stroke="#2ecc71" stroke-width="2"/> <rect x="67" y="95" width="16" height="10" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="30" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="40" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'morning-doji-star',
        title: 'Morning Doji Star (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Identical to Morning Star, but the middle candle is an isolated Doji.',
        psychology: 'Perfect supply-demand equilibrium at the bottom before bulls launch a rally.',
        outcome: 'Extremely potent trend reversal.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="90" x2="75" y2="115" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="102" x2="83" y2="102" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="30" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="40" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-abandoned-baby',
        title: 'Abandoned Baby (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, an isolated Doji gapping below both neighboring candles\' shadows, and a green candle gapping up.',
        psychology: 'True island reversal; sellers trapped completely at the extreme low.',
        outcome: 'Rapid upward repricing via aggressive short covering.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="75" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="92" x2="75" y2="112" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="102" x2="83" y2="102" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="25" x2="110" y2="75" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="35" width="20" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-tri-star',
        title: 'Tri-Star (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three consecutive Dojis with the middle Doji gapping below the other two.',
        psychology: 'Rare sequence marking absolute exhaustion of selling drive.',
        outcome: 'Macro bottom signal; price pivots upward.',
        svgMarkup: '<line x1="40" y1="40" x2="40" y2="70" stroke="#f1c40f" stroke-width="2"/> <line x1="32" y1="55" x2="48" y2="55" stroke="#f1c40f" stroke-width="3"/> <line x1="75" y1="75" x2="75" y2="105" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="90" x2="83" y2="90" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="40" x2="110" y2="70" stroke="#f1c40f" stroke-width="2"/> <line x1="102" y1="55" x2="118" y2="55" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bullish-breakaway',
        title: 'Breakaway (5)',
        bars: 5,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle, gap-down red, 3 smaller declining bodies, followed by a large green candle closing within the original gap.',
        psychology: 'Downward momentum fizzles out; big green candle traps late shorts.',
        outcome: 'Bullish reversal into overhead resistance.',
        svgMarkup: '<line x1="28" y1="20" x2="28" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="21" y="25" width="14" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="50" y1="65" x2="50" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="70" width="12" height="12" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="72" y1="80" x2="72" y2="98" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="83" width="12" height="11" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="94" y1="90" x2="94" y2="108" stroke="#e74c3c" stroke-width="2"/> <rect x="88" y="93" width="12" height="11" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="122" y1="45" x2="122" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="114" y="50" width="16" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-inside-up',
        title: 'Three Inside Up (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Bullish Harami followed by a third green candle closing above Day 2\'s high.',
        psychology: 'Follow-through confirmation validates that buyers have seized command.',
        outcome: 'High-probability long trigger targeting recent swing highs.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="55" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="50" x2="75" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="67" y="60" width="16" height="20" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="20" x2="110" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="28" width="20" height="37" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-outside-up',
        title: 'Three Outside Up (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Bullish Engulfing pattern followed by a third candle closing higher.',
        psychology: 'Rapid confirmation attracts momentum buyers and triggers short stops.',
        outcome: 'Sustained trend reversal with upward acceleration.',
        svgMarkup: '<line x1="40" y1="50" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="32" y="55" width="16" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="30" x2="75" y2="100" stroke="#2ecc71" stroke-width="2"/> <rect x="64" y="40" width="22" height="48" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="100" y="20" width="20" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-kicking',
        title: 'Kicking (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Red Marubozu followed by a green Marubozu that gaps up above Day 1\'s open.',
        psychology: 'Sudden catalyst flips market sentiment 180 degrees overnight.',
        outcome: 'Powerful runaway bullish momentum; shallow pullbacks.',
        svgMarkup: '<line x1="55" y1="60" x2="55" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="43" y="60" width="24" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="50" stroke="#2ecc71" stroke-width="2"/> <rect x="83" y="15" width="24" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'unique-three-rivers-bottom',
        title: 'Unique Three Rivers Bottom (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle; red body with long lower shadow making a new low; small green body trading above the extreme low.',
        psychology: 'Final desperate sell push rejected; selling pressure dissipates.',
        outcome: 'Basing structure leads into an upward reversal.',
        svgMarkup: '<line x1="40" y1="30" x2="40" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="55" x2="75" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="60" width="16" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="70" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="102" y="78" width="16" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'three-stars-in-the-south',
        title: 'Three Stars in the South (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three declining red candles with progressively smaller bodies and higher lows; Day 1 has a long lower wick.',
        psychology: 'Bears make decreasing downward progress each session.',
        outcome: 'Seller burnout; upward bounce expected.',
        svgMarkup: '<line x1="40" y1="30" x2="40" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="30" y="35" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="45" x2="75" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="50" width="18" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="55" x2="110" y2="75" stroke="#e74c3c" stroke-width="2"/> <rect x="102" y="58" width="16" height="14" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'concealing-swallow',
        title: 'Concealing Swallow (4)',
        bars: 4,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Four red candles: two falling Marubozus, an inverted-hammer-like red candle gapping down, engulfed by a fourth red engulfing candle.',
        psychology: 'Climax selling frenzy completely exhausts all remaining supply.',
        outcome: 'Violent short-squeeze snapback rally.',
        svgMarkup: '<line x1="35" y1="25" x2="35" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="27" y="25" width="16" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="60" y1="50" x2="60" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="52" y="50" width="16" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="85" y1="60" x2="85" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="78" y="95" width="14" height="10" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="115" y1="45" x2="115" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="106" y="50" width="18" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-stick-sandwich',
        title: 'Stick Sandwich (3)',
        bars: 3,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Two red candles with identical closing prices sandwiching a green candle.',
        psychology: 'Support level tested twice at the exact same tick and holds.',
        outcome: 'Micro double bottom; strong bounce expected.',
        svgMarkup: '<line x1="40" y1="30" x2="40" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="35" width="18" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="25" x2="75" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="35" width="18" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="30" x2="110" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="35" width="18" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'homing-pigeon',
        title: 'Homing Pigeon (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Long red candle followed by a smaller red candle contained entirely inside Day 1.',
        psychology: 'Sellers are unable to push beyond the prior body; selling momentum dries up.',
        outcome: 'Upward breakout above Day 1 high triggers reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="86" y="55" width="18" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'ladder-bottom',
        title: 'Ladder Bottom (5)',
        bars: 5,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Three declining red bodies, a fourth body with a tall upper wick, followed by a strong green candle gapping up.',
        psychology: 'Downtrend decelerates; Day 4 tests the upside and Day 5 confirms bulls took over.',
        outcome: 'Structural reversal into sustained upward trend.',
        svgMarkup: '<line x1="28" y1="20" x2="28" y2="50" stroke="#e74c3c" stroke-width="2"/> <rect x="22" y="25" width="12" height="23" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="50" y1="42" x2="50" y2="68" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="46" width="12" height="19" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="72" y1="60" x2="72" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="63" width="12" height="19" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="94" y1="62" x2="94" y2="98" stroke="#e74c3c" stroke-width="2"/> <rect x="88" y="80" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="122" y1="30" x2="122" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="114" y="35" width="16" height="43" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'matching-low',
        title: 'Matching Low (2)',
        bars: 2,
        group: 'bullish-reversals',
        groupName: 'Bullish Reversal',
        structure: 'Two consecutive red candles sharing the exact same closing price.',
        psychology: 'Bears fail to close even one tick lower, signaling a solid floor.',
        outcome: 'Support confirmed; expect an immediate relief rally.',
        svgMarkup: '<line x1="55" y1="30" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="45" x2="95" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="50" width="22" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'long-black-body',
        title: 'Long Black Body (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Single tall red candle with a large body appearing after an advance.',
        psychology: 'Heavy selling pressure dominates the session from open to close.',
        outcome: 'Bearish breakdown toward lower support.',
        svgMarkup: '<line x1="75" y1="20" x2="75" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="63" y="35" width="24" height="60" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'hanging-man',
        title: 'Hanging Man (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Small body at the top of an uptrend with a long lower shadow (>= 2x body) and minimal upper shadow.',
        psychology: 'Intraday sell-off reveals emerging supply despite late-session recovery.',
        outcome: 'Bearish reversal confirmed upon a lower close next session.',
        svgMarkup: '<line x1="75" y1="35" x2="75" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="64" y="38" width="22" height="12" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'shooting-star',
        title: 'Shooting Star (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Small real body at the bottom of the range with a long upper shadow (>= 2x body) following an uptrend.',
        psychology: 'Strong morning buying totally rejected by aggressive afternoon distribution.',
        outcome: 'Bearish reversal; short entries triggered beneath the star\'s low.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="64" y="88" width="22" height="12" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-belt-hold',
        title: 'Bearish Belt Hold (1)',
        bars: 1,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Opens on the absolute high of the day (shaved head) and falls steadily to close near the low.',
        psychology: 'Bears seize control immediately at the open with zero upside conceded.',
        outcome: 'Immediate resistance ceiling established; downward continuation expected.',
        svgMarkup: '<line x1="75" y1="25" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="63" y="25" width="24" height="75" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-engulfing',
        title: 'Bearish Engulfing (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Small green body engulfed completely by a tall red real body.',
        psychology: 'Higher open attracts an overwhelming flood of supply, trapping breakout buyers.',
        outcome: 'High reliability downward reversal; stop placed above Day 2 high.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="45" y="55" width="20" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="25" x2="95" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="83" y="35" width="24" height="55" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-harami',
        title: 'Bearish Harami (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Large green candle followed by a smaller red candle contained entirely inside Day 1\'s body.',
        psychology: 'Uptrend hits a wall; buyers fail to expand range beyond prior levels.',
        outcome: 'Trend deceleration; break below Day 1 midpoint confirms reversal.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="86" y="55" width="18" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-harami-cross',
        title: 'Bearish Harami Cross (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a Doji nested completely within Day 1\'s body.',
        psychology: 'Complete standstill at peak prices; buyers and sellers lock in indecision.',
        outcome: 'Potent top turning point; downside break accelerates liquidation.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="43" y="35" width="24" height="60" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="50" x2="95" y2="80" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="65" x2="104" y2="65" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'dark-cloud-cover',
        title: 'Dark Cloud Cover (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a red candle opening above Day 1 high and closing below Day 1\'s midpoint.',
        psychology: 'Gap-up to new highs fails; sellers erase more than 50% of prior gains.',
        outcome: 'High-probability bearish reversal; institutional distribution confirmed.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="35" width="22" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="18" x2="95" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="25" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-doji-star',
        title: 'Bearish Doji Star (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a Doji that gaps above Day 1\'s body.',
        psychology: 'Bullish gap-up stalls completely; buyers fail to achieve any forward progress.',
        outcome: 'Early alert of top exhaustion; confirmation candle triggers short positions.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="55" width="22" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="42" stroke="#f1c40f" stroke-width="2"/> <line x1="86" y1="28" x2="104" y2="28" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bearish-meeting-lines',
        title: 'Bearish Meeting Lines (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by a red candle opening sharply higher but closing at the exact same price as Day 1\'s close.',
        psychology: 'Bullish opening surge is met with ferocious counter-selling returning price to parity.',
        outcome: 'Advance stopped cold; downward reversal expected.',
        svgMarkup: '<line x1="55" y1="45" x2="55" y2="100" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="50" width="22" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="20" width="22" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'three-black-crows',
        title: 'Three Black Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive long red candles, each opening within the prior body and closing lower near lows.',
        psychology: 'Sustained institutional liquidation overwhelms all remaining buyers.',
        outcome: 'Powerful top reversal initiating an extended downward trend.',
        svgMarkup: '<line x1="40" y1="20" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="25" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="45" x2="75" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="50" width="18" height="33" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="70" x2="110" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="75" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'evening-star',
        title: 'Evening Star (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, upward gapping small body, and a long red candle closing deeply into Day 1.',
        psychology: 'Bullish euphoria pauses in hesitation before sellers take firm control.',
        outcome: 'Major cyclical top reversal; high-probability short opportunity.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="50" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="42" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="22" width="16" height="10" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="35" x2="110" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="45" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'evening-doji-star',
        title: 'Evening Doji Star (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Identical to Evening Star, but the apex candle is an isolated Doji.',
        psychology: 'Peak supply-demand equilibrium followed by swift long liquidation.',
        outcome: 'Very potent top reversal pattern; downward momentum expands rapidly.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="50" width="20" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="40" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="28" x2="83" y2="28" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="35" x2="110" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="45" width="20" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-abandoned-baby',
        title: 'Bearish Abandoned Baby (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, isolated Doji gapping above both neighbors\' shadows, and a red candle gapping down.',
        psychology: 'Island reversal; buyers trapped on an island at the extreme high.',
        outcome: 'Panic selling and rapid downside cascade.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="60" width="20" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="38" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="26" x2="83" y2="26" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="55" x2="110" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="60" width="20" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-tri-star',
        title: 'Bearish Tri-Star (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive Dojis with the middle Doji gapping above the outer two.',
        psychology: 'Extreme exhaustion of buying power at resistance.',
        outcome: 'Macro top signal; price rotates downward.',
        svgMarkup: '<line x1="40" y1="60" x2="40" y2="90" stroke="#f1c40f" stroke-width="2"/> <line x1="32" y1="75" x2="48" y2="75" stroke="#f1c40f" stroke-width="3"/> <line x1="75" y1="25" x2="75" y2="55" stroke="#f1c40f" stroke-width="2"/> <line x1="67" y1="40" x2="83" y2="40" stroke="#f1c40f" stroke-width="3"/> <line x1="110" y1="60" x2="110" y2="90" stroke="#f1c40f" stroke-width="2"/> <line x1="102" y1="75" x2="118" y2="75" stroke="#f1c40f" stroke-width="3"/>',
    },
    {
        id: 'bearish-breakaway',
        title: 'Bearish Breakaway (5)',
        bars: 5,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, gap-up green, 3 smaller advancing bodies, followed by a large red candle closing within the original gap.',
        psychology: 'Upward momentum decelerates until a large red candle traps late buyers.',
        outcome: 'Bearish reversal breaking into underlying support.',
        svgMarkup: '<line x1="28" y1="70" x2="28" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="21" y="75" width="14" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="50" y1="45" x2="50" y2="65" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="48" width="12" height="12" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="72" y1="32" x2="72" y2="50" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="35" width="12" height="11" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="94" y1="22" x2="94" y2="40" stroke="#2ecc71" stroke-width="2"/> <rect x="88" y="25" width="12" height="11" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="122" y1="25" x2="122" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="114" y="30" width="16" height="50" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'three-inside-down',
        title: 'Three Inside Down (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Bearish Harami followed by a third red candle closing below Day 2\'s low.',
        psychology: 'Follow-through confirmation validates that sellers hold full market control.',
        outcome: 'High-probability short entry targeting recent swing support.',
        svgMarkup: '<line x1="40" y1="25" x2="40" y2="100" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="35" width="20" height="55" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="45" x2="75" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="50" width="16" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="60" x2="110" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="65" width="20" height="37" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'three-outside-down',
        title: 'Three Outside Down (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Bearish Engulfing pattern followed by a third candle closing lower.',
        psychology: 'Immediate continuation prompts cascading stop-loss selling.',
        outcome: 'Sustained downward trend with acceleration.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="32" y="50" width="16" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="30" x2="75" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="64" y="38" width="22" height="48" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="75" x2="110" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="100" y="80" width="20" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-kicking',
        title: 'Bearish Kicking (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Green Marubozu followed by a red Marubozu that gaps down beneath Day 1\'s open.',
        psychology: 'Severe overnight catalyst flips market sentiment completely downward.',
        outcome: 'Violent runaway bearish trend; any bounce is short-lived.',
        svgMarkup: '<line x1="55" y1="15" x2="55" y2="65" stroke="#2ecc71" stroke-width="2"/> <rect x="43" y="15" width="24" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="83" y="75" width="24" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'latter-top',
        title: 'Latter Top (5)',
        bars: 5,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three advancing green bodies, a fourth body with a tall upper wick, followed by a red candle opening lower.',
        psychology: 'Uptrend exhausts on Day 4; Day 5 confirms rejection of higher prices.',
        outcome: 'Structural top; bearish trend reversal initiated.',
        svgMarkup: '<line x1="28" y1="80" x2="28" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="22" y="82" width="12" height="23" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="50" y1="62" x2="50" y2="88" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="65" width="12" height="19" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="72" y1="45" x2="72" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="48" width="12" height="19" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="94" y1="22" x2="94" y2="58" stroke="#2ecc71" stroke-width="2"/> <rect x="88" y="35" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="122" y1="45" x2="122" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="114" y="52" width="16" height="43" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'matching-high',
        title: 'Matching High (2)',
        bars: 2,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Two consecutive green candles sharing the exact same closing price.',
        psychology: 'Resistance proves impenetrable; buyers fail to close even one tick higher.',
        outcome: 'Double-top ceiling confirmed; downward correction expected.',
        svgMarkup: '<line x1="55" y1="35" x2="55" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="40" width="22" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="35" x2="95" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="40" width="22" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'upside-gap-two-crows',
        title: 'Upside Gap Two Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle, upward-gapping small red body, and a second red body engulfing Day 2 while remaining above Day 1 close.',
        psychology: 'Gap-up fails to hold; two consecutive down sessions reveal latent distribution.',
        outcome: 'Bearish reversal breaking into the gap zone.',
        svgMarkup: '<line x1="40" y1="40" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="45" width="20" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="42" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="20" width="16" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="44" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="18" width="18" height="24" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'identical-three-crows',
        title: 'Identical Three Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive red candles where each candle opens at or very near the preceding candle\'s close.',
        psychology: 'Relentless cascade of selling pressure with zero intraday rebounds.',
        outcome: 'Severe bearish momentum; ongoing trend down.',
        svgMarkup: '<line x1="40" y1="20" x2="40" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="25" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="50" x2="75" y2="90" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="55" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="80" x2="110" y2="120" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="85" width="18" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'deliberation',
        title: 'Deliberation (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Two long green candles followed by a third small green body (or star) opening higher.',
        psychology: 'Rapid advance suddenly slows as buyers deliberate on valuation.',
        outcome: 'Trend exhaustion warning; imminent stall or sharp pullback.',
        svgMarkup: '<line x1="40" y1="45" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="50" width="18" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="25" x2="75" y2="75" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="30" width="18" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="35" stroke="#2ecc71" stroke-width="2"/> <rect x="102" y="18" width="16" height="10" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'advance-block',
        title: 'Advance Block (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Three consecutive green candles making new highs, with diminishing real bodies and expanding upper shadows.',
        psychology: 'Stiffening overhead supply repeatedly pushes buyers off the session highs.',
        outcome: 'Rally stalls; high probability of trend reversal.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="35" x2="75" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="45" width="18" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="18" x2="110" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="40" width="18" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'two-crows',
        title: 'Two Crows (3)',
        bars: 3,
        group: 'bearish-reversals',
        groupName: 'Bearish Reversal',
        structure: 'Long green candle followed by an upward-gapping small red candle, and a second red candle that opens in Day 2 and closes inside Day 1.',
        psychology: 'Gap-up fails to hold; bears penetrate deeply into Day 1 gains.',
        outcome: 'Trend reversal confirmed; sell-off toward baseline support.',
        svgMarkup: '<line x1="40" y1="40" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="30" y="45" width="20" height="50" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="45" stroke="#e74c3c" stroke-width="2"/> <rect x="67" y="20" width="16" height="18" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="25" x2="110" y2="70" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="28" width="18" height="32" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-separating-lines',
        title: 'Bullish Separating Lines (2)',
        bars: 2,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Red candle in an uptrend followed by a green candle that opens at the exact same price as Day 1\'s open and rallies.',
        psychology: 'Bears mount a counter-attack, but bulls instantly reclaim the open and surge higher.',
        outcome: 'Powerful bullish continuation; uptrend resumes with conviction.',
        svgMarkup: '<line x1="55" y1="35" x2="55" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="45" width="22" height="40" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="20" width="22" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'rising-three-methods',
        title: 'Rising Three Methods (5)',
        bars: 5,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Long green candle, 3 small declining red candles held within Day 1\'s high-low range, followed by a strong green breakout candle.',
        psychology: 'Routine profit-taking is cleanly absorbed; buyers trigger the next expansion leg.',
        outcome: 'Classic continuation pattern; upward trend resumes immediately.',
        svgMarkup: '<line x1="25" y1="25" x2="25" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="18" y="30" width="14" height="65" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="48" y1="35" x2="48" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="42" y="38" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="68" y1="45" x2="68" y2="70" stroke="#e74c3c" stroke-width="2"/> <rect x="62" y="48" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="88" y1="55" x2="88" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="82" y="58" width="12" height="15" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="115" y1="15" x2="115" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="108" y="20" width="14" height="65" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'upside-tasuki-gap',
        title: 'Upside Tasuki Gap (3)',
        bars: 3,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Green candle, upward-gapping green candle, followed by a red candle closing into the gap without completely filling it.',
        psychology: 'Mild pullback tests the gap support where aggressive buyers step in.',
        outcome: 'Unfilled gap validates strong upward momentum; buy on gap retest.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="18" x2="75" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="22" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="28" x2="110" y2="70" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="32" width="18" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-side-by-side-white-lines',
        title: 'Bullish Side-by-Side White Lines (3)',
        bars: 3,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Green candle followed by two side-by-side green candles that gap up and share similar opens and body heights.',
        psychology: 'Demand remains robust at higher prices; sellers are completely absent.',
        outcome: 'Strong bullish continuation with upward targets.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="20" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="15" x2="110" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="20" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-three-line-strike',
        title: 'Bullish Three Line Strike (4)',
        bars: 4,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Three advancing green candles followed by a massive red candle that engulfs all three prior bodies.',
        psychology: 'Sudden liquidity flush shakes out leveraged longs right before institutional continuation.',
        outcome: 'Counter-intuitive continuation pattern; uptrend typically restarts rapidly.',
        svgMarkup: '<line x1="30" y1="65" x2="30" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="23" y="70" width="14" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="55" y1="45" x2="55" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="48" y="50" width="14" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="80" y1="25" x2="80" y2="65" stroke="#2ecc71" stroke-width="2"/> <rect x="73" y="30" width="14" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="115" y1="18" x2="115" y2="110" stroke="#e74c3c" stroke-width="2"/> <rect x="107" y="25" width="16" height="78" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'upside-gap-three-methods',
        title: 'Upside Gap Three Methods (3)',
        bars: 3,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Two rising green candles with an upside gap, followed by a red candle that completely fills the gap.',
        psychology: 'Healthy gap-filling pullback clears order book before the next rally leg.',
        outcome: 'Gap filled; strong upward resumption from newly tested support.',
        svgMarkup: '<line x1="40" y1="55" x2="40" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="31" y="60" width="18" height="35" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="75" y1="15" x2="75" y2="55" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="20" width="18" height="28" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="25" x2="110" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="101" y="30" width="18" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bullish-on-neck-line',
        title: 'Bullish On Neck Line (2)',
        bars: 2,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Red candle in an uptrend followed by a green candle opening lower and closing precisely at Day 1\'s low.',
        psychology: 'Minor dip stabilizes cleanly at prior support; sellers fail to press lower.',
        outcome: 'Moderate bullish continuation once price crosses above Day 1 high.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="75" x2="95" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="80" width="22" height="22" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bullish-in-neck-line',
        title: 'Bullish In Neck Line (2)',
        bars: 2,
        group: 'bullish-continuations',
        groupName: 'Bullish Continuation',
        structure: 'Red candle followed by a green candle opening lower and closing slightly inside Day 1\'s real body.',
        psychology: 'Selling pressure falters quickly; buyers absorb shallow pullback.',
        outcome: 'Bullish continuation confirmed when price clears the Day 1 high.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#e74c3c" stroke-width="2"/> <rect x="44" y="35" width="22" height="45" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="95" y1="65" x2="95" y2="110" stroke="#2ecc71" stroke-width="2"/> <rect x="84" y="70" width="22" height="30" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-separating-lines',
        title: 'Bearish Separating Lines (2)',
        bars: 2,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Green candle in a downtrend followed by a red candle that opens at the exact same price as Day 1\'s open and falls.',
        psychology: 'Short-lived bounce is instantly crushed; sellers assert undisputed authority.',
        outcome: 'Reliable bearish continuation; downtrend accelerates into new lows.',
        svgMarkup: '<line x1="55" y1="25" x2="55" y2="85" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="35" width="22" height="40" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="65" x2="95" y2="115" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="75" width="22" height="30" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'falling-three-methods',
        title: 'Falling Three Methods (5)',
        bars: 5,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Long red candle, 3 small green candles held entirely within Day 1\'s range, followed by a long red candle closing to a new low.',
        psychology: 'Feeble counter-trend rally runs out of steam; bears resume intense selling.',
        outcome: 'Textbook bearish continuation; breakdown below swing lows.',
        svgMarkup: '<line x1="25" y1="15" x2="25" y2="95" stroke="#e74c3c" stroke-width="2"/> <rect x="18" y="20" width="14" height="65" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="48" y1="55" x2="48" y2="80" stroke="#2ecc71" stroke-width="2"/> <rect x="42" y="58" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="68" y1="45" x2="68" y2="70" stroke="#2ecc71" stroke-width="2"/> <rect x="62" y="48" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="88" y1="35" x2="88" y2="60" stroke="#2ecc71" stroke-width="2"/> <rect x="82" y="38" width="12" height="15" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="115" y1="25" x2="115" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="108" y="30" width="14" height="65" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'downside-tasuki-gap',
        title: 'Downside Tasuki Gap (3)',
        bars: 3,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Red candle, downward-gapping red candle, followed by a green candle closing into the gap without completely filling it.',
        psychology: 'Weak short-covering bounce stalls directly at gap resistance where fresh sellers reload.',
        outcome: 'Unfilled gap acts as rigid resistance; downward trend continues.',
        svgMarkup: '<line x1="40" y1="18" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="22" width="18" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="65" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="70" width="18" height="28" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="50" x2="110" y2="90" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="55" width="18" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-side-by-side-white-lines',
        title: 'Bearish Side-by-Side White Lines (3)',
        bars: 3,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Red candle followed by two side-by-side green candles that gap down below Day 1\'s low and share matching levels.',
        psychology: 'Two consecutive green days cannot penetrate above the gap; bears retain total dominance.',
        outcome: 'Highly reliable bearish continuation; downward resumption expected.',
        svgMarkup: '<line x1="40" y1="15" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="20" width="18" height="38" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="65" x2="75" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="66" y="72" width="18" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="110" y1="65" x2="110" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="72" width="18" height="25" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-three-line-strike',
        title: 'Bearish Three Line Strike (4)',
        bars: 4,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Three declining red candles followed by a massive green candle that opens lower and engulfs all three prior bodies.',
        psychology: 'Violently squeezes short positions before the prevailing downward trend resumes.',
        outcome: 'Counter-intuitive continuation pattern; downtrend restarts quickly.',
        svgMarkup: '<line x1="30" y1="20" x2="30" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="23" y="25" width="14" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="55" y1="40" x2="55" y2="80" stroke="#e74c3c" stroke-width="2"/> <rect x="48" y="45" width="14" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="80" y1="60" x2="80" y2="100" stroke="#e74c3c" stroke-width="2"/> <rect x="73" y="65" width="14" height="25" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="115" y1="15" x2="115" y2="105" stroke="#2ecc71" stroke-width="2"/> <rect x="107" y="20" width="16" height="78" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'downside-gap-three-methods',
        title: 'Downside Gap Three Methods (3)',
        bars: 3,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Two falling red candles separated by a downward gap, followed by a green candle that rallies to close the gap completely.',
        psychology: 'Gap fill creates optimal shorting liquidity at resistance for institutional bears.',
        outcome: 'Gap resistance rejected; steep downtrend resumes.',
        svgMarkup: '<line x1="40" y1="15" x2="40" y2="65" stroke="#e74c3c" stroke-width="2"/> <rect x="31" y="20" width="18" height="35" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="75" y1="65" x2="75" y2="105" stroke="#e74c3c" stroke-width="2"/> <rect x="66" y="70" width="18" height="28" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/> <line x1="110" y1="35" x2="110" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="101" y="40" width="18" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/>',
    },
    {
        id: 'bearish-on-neck-line',
        title: 'Bearish On Neck Line (2)',
        bars: 2,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'In a downtrend, a green candle is met by a red candle opening higher and closing precisely at Day 1\'s high.',
        psychology: 'Intraday rally gets completely repulsed right at the neckline resistance.',
        outcome: 'Downward continuation; failure to break through resistance resumes sell-off.',
        svgMarkup: '<line x1="55" y1="35" x2="55" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="40" width="22" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="55" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="20" width="22" height="20" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
    {
        id: 'bearish-in-neck-line',
        title: 'Bearish In Neck Line (2)',
        bars: 2,
        group: 'bearish-continuations',
        groupName: 'Bearish Continuation',
        structure: 'Green candle followed by a red candle opening higher and penetrating barely into Day 1\'s real body.',
        psychology: 'Weak penetration fails to spark any buying conviction; bears maintain control.',
        outcome: 'Downtrend continuation; break below Day 1 low initiates next leg lower.',
        svgMarkup: '<line x1="55" y1="35" x2="55" y2="95" stroke="#2ecc71" stroke-width="2"/> <rect x="44" y="40" width="22" height="45" fill="#2ecc71" rx="1" stroke="#1b7a43" stroke-width="1"/> <line x1="95" y1="15" x2="95" y2="60" stroke="#e74c3c" stroke-width="2"/> <rect x="84" y="22" width="22" height="22" fill="#e74c3c" rx="1" stroke="#b30000" stroke-width="1"/>',
    },
];

export interface CandlestickGroup {
    id: 'bullish-reversals' | 'bearish-reversals' | 'bullish-continuations' | 'bearish-continuations';
    title: string;
    subtitle: string;
    badgeClass: string;
}

export const CANDLESTICK_GROUPS: CandlestickGroup[] = [
    {
        id: 'bullish-reversals',
        title: 'Part I: Bullish Reversals',
        subtitle: 'Appears at the bottom of a downtrend; signals sellers are exhausted and buyers are taking control.',
        badgeClass: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/20',
    },
    {
        id: 'bearish-reversals',
        title: 'Part II: Bearish Reversals',
        subtitle: 'Appears at the peak of an uptrend; signals buyers are exhausted and distribution is underway.',
        badgeClass: 'bg-rose-500/15 text-rose-400 border border-rose-500/20',
    },
    {
        id: 'bullish-continuations',
        title: 'Part III: Bullish Continuations',
        subtitle: 'Appears during an uptrend; represents consolidation before upward resumption.',
        badgeClass: 'bg-blue-500/15 text-blue-400 border border-blue-500/20',
    },
    {
        id: 'bearish-continuations',
        title: 'Part IV: Bearish Continuations',
        subtitle: 'Appears during a downtrend; represents temporary pause or pullback before downward resumption.',
        badgeClass: 'bg-amber-500/15 text-amber-400 border border-amber-500/20',
    },
];

const norm = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const LOOKUP_MAP = new Map<string, CandlestickPatternDetail>();

for (const p of CANDLESTICK_PATTERNS) {
    LOOKUP_MAP.set(p.id, p);
    LOOKUP_MAP.set(norm(p.id), p);
    LOOKUP_MAP.set(norm(p.title), p);
    const titleWithoutBars = p.title.replace(/\s*\(\d+\)/, '');
    LOOKUP_MAP.set(norm(titleWithoutBars), p);
    // Explicit full names with prefix
    if (p.group.startsWith('bullish')) {
        LOOKUP_MAP.set('bullish' + norm(titleWithoutBars), p);
    } else if (p.group.startsWith('bearish')) {
        LOOKUP_MAP.set('bearish' + norm(titleWithoutBars), p);
    }
}

export function getCandlestickPatternDetails(
    pattern: { longName?: string; shortName?: string; sentiment?: string } | null | undefined
): CandlestickPatternDetail | null {
    if (!pattern) return null;
    if (pattern.longName) {
        const direct = LOOKUP_MAP.get(norm(pattern.longName));
        if (direct) return direct;
        if (pattern.sentiment) {
            const prefix = pattern.sentiment.toLowerCase().startsWith('bullish') ? 'bullish' : 'bearish';
            const withPrefix = LOOKUP_MAP.get(prefix + norm(pattern.longName));
            if (withPrefix) return withPrefix;
        }
        const clean = norm(pattern.longName).replace(/^bullish/, '').replace(/^bearish/, '');
        const fallback = LOOKUP_MAP.get(clean);
        if (fallback) return fallback;
    }
    return null;
}
