CREATE TABLE tickers
(
    ticker_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE         NOT NULL,
    symbol     VARCHAR(20)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL
);

CREATE TABLE files
(
    file_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id     INT                   NOT NULL,
    file_date     DATE                  NOT NULL,
    file_url      TEXT                  NOT NULL,
    is_downloaded BOOLEAN DEFAULT FALSE NOT NULL,
    is_processed  BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE market_data_daily
(
    market_data_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id           INT  NOT NULL,
    market_data_date          DATE NOT NULL,
    price_open          NUMERIC(18, 8),
    price_high          NUMERIC(18, 8),
    price_low           NUMERIC(18, 8),
    price_close         NUMERIC(18, 8),
    volume              NUMERIC(28, 8),
    vwap                NUMERIC(18, 8),
    volume_profile_poc    NUMERIC(18, 8),
    volume_profile_vah    NUMERIC(18, 8),
    volume_profile_val    NUMERIC(18, 8),
    buyer_volume_share  DOUBLE PRECISION,
    buyer_capital_share DOUBLE PRECISION
);

CREATE TABLE market_state_daily (
	market_state_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ticker_id           INT  NOT NULL,
	market_state_date DATE NOT NULL,
	metric VARCHAR(100) NOT NULL,
	ma_type VARCHAR(8) NOT NULL,
	period INT  NOT NULL,
	value NUMERIC(28, 8) NOT NULL
);
