CREATE TABLE tickers
(
    ticker_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_date   DATE         NOT NULL,

    ticker_symbol VARCHAR(20)  NOT NULL UNIQUE,
    ticker_name   VARCHAR(100) NOT NULL
);

CREATE TABLE files
(
    file_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_date    DATE                  NOT NULL,

    ticker_id    INT                   NOT NULL,
    file_url     TEXT                  NOT NULL,
    is_processed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE market_data
(
    market_data_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_data_date    DATE           NOT NULL,

    ticker_id           INT            NOT NULL,
    price_open          NUMERIC(28, 8) NOT NULL,
    price_high          NUMERIC(28, 8) NOT NULL,
    price_low           NUMERIC(28, 8) NOT NULL,
    price_close         NUMERIC(28, 8) NOT NULL,
    volume              NUMERIC(38, 8) NOT NULL,
    vwap                NUMERIC(28, 8) NOT NULL,
    volume_profile_poc  NUMERIC(28, 8) NOT NULL,
    volume_profile_vah  NUMERIC(28, 8) NOT NULL,
    volume_profile_val  NUMERIC(28, 8) NOT NULL,
    buyer_volume_share  NUMERIC(10, 8) NOT NULL,
    buyer_capital_share NUMERIC(10, 8) NOT NULL
);

CREATE TABLE market_state
(
    market_state_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_state_date DATE           NOT NULL,

    ticker_id         INT            NOT NULL,
    metric            VARCHAR(100)   NOT NULL,
    ma_type           VARCHAR(16)    NOT NULL,
    period            INT            NOT NULL,
    value             NUMERIC(28, 8) NOT NULL
);
