CREATE TABLE renko_data
(
    renko_data_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renko_date    DATE           NOT NULL,
    ticker_id     INT            NOT NULL,
    brick_low     NUMERIC(28, 8) NOT NULL,
    brick_high    NUMERIC(28, 8) NOT NULL,
    direction     VARCHAR(10)    NOT NULL,
    trend         INT            NOT NULL,
    FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id)
);

CREATE INDEX idx_renko_data_ticker ON renko_data (ticker_id);
