-- ==========================================
-- 4. INDICATOR TABLES
-- ==========================================
-- Precomputed technical indicators (EMA, SMA, RSI, MACD, Stochastic, ...) and the
-- per-combo resume checkpoints that make incremental computation possible.
-- See docs/indicators-design.md for the full design and rationale.

-- Published plot values (what the API serves). One row per plot:
--   SMA/EMA/RSI -> 1 (output_name 'value'), MACD -> 3 (macd/signal/histogram),
--   Stochastic -> 2 (k/d). value is NOT NULL: no rows are stored during the warm-up period.
CREATE TABLE public.indicator_values
(
    indicator_value_id bigint         NOT NULL,
    ticker_id          bigint         NOT NULL,
    timeframe          varchar(16)    NOT NULL,
    indicator_type     varchar(32)    NOT NULL,
    source             varchar(16)    NOT NULL,
    params             varchar(128)   NOT NULL,
    output_name        varchar(32)    NOT NULL,
    price_date         date           NOT NULL,
    value              numeric(18, 4) NOT NULL,

    CONSTRAINT indicator_values_pkey PRIMARY KEY (indicator_value_id),
    CONSTRAINT uk_indicator_values UNIQUE (ticker_id, timeframe, indicator_type, source, params, output_name, price_date)
);
ALTER TABLE public.indicator_values
    ALTER COLUMN indicator_value_id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.indicator_values_id_seq);


-- Resume checkpoints (internal). One row per (ticker, timeframe, indicator, source, params).
-- Every combo has a row, including windowed indicators (SMA/Stochastic) that leave internals NULL,
-- so cold-start detection and the contiguity check are uniform. last_price_date always lags the
-- latest published bar by >= 1 finalized bar (the in-progress bar is never checkpointed).
-- internals holds recursive running state as string-encoded decimals for bit-exact resume.
CREATE TABLE public.indicator_state
(
    indicator_state_id bigint       NOT NULL,
    ticker_id          bigint       NOT NULL,
    timeframe          varchar(16)  NOT NULL,
    indicator_type     varchar(32)  NOT NULL,
    source             varchar(16)  NOT NULL,
    params             varchar(128) NOT NULL,
    last_price_date    date         NOT NULL,
    internals          jsonb,

    CONSTRAINT indicator_state_pkey PRIMARY KEY (indicator_state_id),
    CONSTRAINT uk_indicator_state UNIQUE (ticker_id, timeframe, indicator_type, source, params)
);
ALTER TABLE public.indicator_state
    ALTER COLUMN indicator_state_id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.indicator_state_id_seq);


-- Foreign keys
ALTER TABLE ONLY public.indicator_values
    ADD CONSTRAINT fk_indicator_values_tickers FOREIGN KEY (ticker_id)
        REFERENCES public.tickers (ticker_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.indicator_state
    ADD CONSTRAINT fk_indicator_state_tickers FOREIGN KEY (ticker_id)
        REFERENCES public.tickers (ticker_id) ON DELETE CASCADE;


-- Lookup index: bulk-by-timeframe API reads (ticker, timeframe) newest-first.
CREATE INDEX idx_indicator_values_lookup
    ON public.indicator_values USING btree (ticker_id, timeframe, price_date DESC);
