CREATE TABLE public.analysis_results
(
    analysis_id        bigint         NOT NULL,
    ticker_id          bigint         NOT NULL,
    price_date         date           NOT NULL,
    ema_signal         varchar(32)    NOT NULL,
    ema_value          varchar(255)   NOT NULL,
    macd_signal        varchar(32)    NOT NULL,
    macd_value         varchar(255)   NOT NULL,
    stochastic_signal  varchar(32)    NOT NULL,
    stochastic_value   varchar(255)   NOT NULL,
    rsi_signal         varchar(32)    NOT NULL,
    rsi_value          varchar(255)   NOT NULL,
    volume_signal      varchar(32)    NOT NULL,
    volume_value       varchar(255)   NOT NULL,
    overall_signal     varchar(32)    NOT NULL,

    CONSTRAINT analysis_results_pkey PRIMARY KEY (analysis_id),
    CONSTRAINT uk_analysis_results UNIQUE (ticker_id),
    CONSTRAINT fk_analysis_results_tickers FOREIGN KEY (ticker_id)
        REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

ALTER TABLE public.analysis_results
    ALTER COLUMN analysis_id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.analysis_results_id_seq);
