-- Migration to refactor backtest results persistence

-- 1. Create backtest_equity table
CREATE TABLE backtest_equity
(
    backtest_equity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id          INT            NOT NULL,
    strategy_name      VARCHAR(255)   NOT NULL,
    equity_date        DATE           NOT NULL,
    equity             NUMERIC(28, 8) NOT NULL,
    position           VARCHAR(50)    NOT NULL,
    price_close        NUMERIC(28, 8) NOT NULL,
    CONSTRAINT fk_equity_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE
);

-- 2. Create backtest_signal table
CREATE TABLE backtest_signal
(
    backtest_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id          INT          NOT NULL,
    strategy_name      VARCHAR(255) NOT NULL,
    signal_date        DATE         NOT NULL,
    execute_date       DATE,
    action             VARCHAR(50)  NOT NULL,
    from_position      VARCHAR(50)  NOT NULL,
    to_position        VARCHAR(50)  NOT NULL,
    CONSTRAINT fk_signal_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE
);

-- 3. Create backtest_trade table
CREATE TABLE backtest_trade
(
    backtest_trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id         INT            NOT NULL,
    strategy_name     VARCHAR(255)   NOT NULL,
    side              VARCHAR(50)    NOT NULL,
    entry_date        DATE           NOT NULL,
    entry_price       NUMERIC(28, 8) NOT NULL,
    exit_date         DATE,
    exit_price        NUMERIC(28, 8),
    quantity          NUMERIC(28, 8) NOT NULL,
    pnl               NUMERIC(28, 8),
    pnl_pct           NUMERIC(28, 8),
    holding_bars      INTEGER,
    CONSTRAINT fk_trade_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE
);

-- 4. Create backtest_cagr table
CREATE TABLE backtest_cagr
(
    backtest_cagr_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id        INT            NOT NULL,
    strategy_name    VARCHAR(255)   NOT NULL,
    initial_equity   NUMERIC(28, 8) NOT NULL,
    final_equity     NUMERIC(28, 8) NOT NULL,
    start_date       DATE           NOT NULL,
    end_date         DATE           NOT NULL,
    years            NUMERIC(28, 8) NOT NULL,
    cagr             NUMERIC(28, 8) NOT NULL,
    CONSTRAINT fk_cagr_ticker FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE
);

-- 5. Remove old backtests table
DROP TABLE IF EXISTS backtests;
