-- Reverse migration for backtest results persistence refactor

-- 1. Re-create old backtests table
CREATE TABLE backtests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_date DATE           NOT NULL,
    ticker_id     INT            NOT NULL,
    strategy_name VARCHAR(100)   NOT NULL,
    equity        NUMERIC(28, 8) NOT NULL,
    position      VARCHAR(20)    NOT NULL,
    price         NUMERIC(28, 8) NOT NULL,
    signal        VARCHAR(20)    NOT NULL
);

ALTER TABLE backtests
    ADD CONSTRAINT fk_backtests_tickers
        FOREIGN KEY (ticker_id)
            REFERENCES tickers (ticker_id)
            ON DELETE CASCADE;

ALTER TABLE backtests
    ADD CONSTRAINT uk_backtests UNIQUE (backtest_date, ticker_id, strategy_name);

-- 2. Drop new tables
DROP TABLE IF EXISTS backtest_cagr;
DROP TABLE IF EXISTS backtest_trade;
DROP TABLE IF EXISTS backtest_signal_intent;
DROP TABLE IF EXISTS backtest_equity_daily;
