-- ==========================================
-- 7. RECREATE INDICATOR STATE TABLE (DOWN)
-- ==========================================
CREATE TABLE public.indicator_state
(
    indicator_state_id bigint       NOT NULL,
    ticker_id          bigint       NOT NULL,
    timeframe          varchar(16)  NOT NULL,
    indicator_type     varchar(32)  NOT NULL,
    source             varchar(16)  NOT NULL,
    params             varchar(128) NOT NULL,
    last_price_date    date         NOT NULL,
    internals          jsonb,

    CONSTRAINT indicator_state_pkey PRIMARY KEY (indicator_state_id),
    CONSTRAINT uk_indicator_state UNIQUE (ticker_id, timeframe, indicator_type, source, params)
);

ALTER TABLE public.indicator_state
    ALTER COLUMN indicator_state_id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.indicator_state_id_seq);

ALTER TABLE ONLY public.indicator_state
    ADD CONSTRAINT fk_indicator_state_tickers FOREIGN KEY (ticker_id)
        REFERENCES public.tickers (ticker_id) ON DELETE CASCADE;
