-- ==========================================
-- 8. INDICATOR DEFINITIONS REFACTORING
-- ==========================================

-- 1. Create the new indicator_definitions table
CREATE TABLE public.indicator_definitions
(
    indicator_id   bigint         NOT NULL,
    timeframe      varchar(16)    NOT NULL,
    indicator_type varchar(32)    NOT NULL,
    source         varchar(16)    NOT NULL,
    params         jsonb          NOT NULL,

    CONSTRAINT indicator_definitions_pkey PRIMARY KEY (indicator_id),
    CONSTRAINT uk_indicator_definitions UNIQUE (timeframe, indicator_type, source, params)
);
ALTER TABLE public.indicator_definitions
    ALTER COLUMN indicator_id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.indicator_definitions_id_seq);

-- 2. Clear existing indicator values
TRUNCATE TABLE public.indicator_values;

-- 3. Drop columns from indicator_values that have moved to definitions
ALTER TABLE public.indicator_values DROP COLUMN timeframe;
ALTER TABLE public.indicator_values DROP COLUMN indicator_type;
ALTER TABLE public.indicator_values DROP COLUMN source;
ALTER TABLE public.indicator_values DROP COLUMN params;

-- 4. Add indicator_id column to indicator_values
ALTER TABLE public.indicator_values ADD COLUMN indicator_id bigint NOT NULL;

-- 5. Add foreign key to indicator_definitions
ALTER TABLE ONLY public.indicator_values
    ADD CONSTRAINT fk_indicator_values_definitions FOREIGN KEY (indicator_id)
        REFERENCES public.indicator_definitions (indicator_id) ON DELETE CASCADE;

-- 6. Recreate the unique constraint on indicator_values
ALTER TABLE public.indicator_values DROP CONSTRAINT IF EXISTS uk_indicator_values;
ALTER TABLE public.indicator_values
    ADD CONSTRAINT uk_indicator_values UNIQUE (ticker_id, indicator_id, price_date, output_name);

-- 7. Recreate the lookup index on indicator_values
DROP INDEX IF EXISTS public.idx_indicator_values_lookup;
CREATE INDEX idx_indicator_values_lookup
    ON public.indicator_values USING btree (ticker_id, indicator_id, price_date DESC);
