-- ==========================================
-- 11. REVERT: SPLIT INDICATOR VALUES
-- ==========================================

DROP TABLE IF EXISTS public.daily_indicators CASCADE;
DROP TABLE IF EXISTS public.weekly_indicators CASCADE;

CREATE TABLE public.indicator_values (
    indicator_value_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ticker_id bigint NOT NULL,
    indicator_id bigint NOT NULL,
    price_date date NOT NULL,
    values jsonb NOT NULL,
    CONSTRAINT indicator_values_pkey PRIMARY KEY (indicator_value_id),
    CONSTRAINT uk_indicator_values UNIQUE (ticker_id, indicator_id, price_date),
    CONSTRAINT fk_indicator_values_tickers FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT fk_indicator_values_definitions FOREIGN KEY (indicator_id) REFERENCES public.indicator_definitions (indicator_id) ON DELETE CASCADE
);

CREATE INDEX idx_indicator_values_lookup
    ON public.indicator_values USING btree (ticker_id, indicator_id, price_date DESC);
