-- ==========================================
-- 11. SPLIT INDICATOR VALUES INTO TIME FRAMES
-- ==========================================

-- 1. Drop old table
DROP TABLE IF EXISTS public.indicator_values CASCADE;

-- 2. Create daily_indicators table
CREATE TABLE public.daily_indicators (
    daily_indicator_id bigint GENERATED BY DEFAULT AS IDENTITY,
    indicator_id bigint NOT NULL,
    ticker_id bigint NOT NULL,
    price_date date NOT NULL,
    values jsonb NOT NULL,
    CONSTRAINT daily_indicators_pkey PRIMARY KEY (daily_indicator_id),
    CONSTRAINT uk_daily_indicators UNIQUE (ticker_id, indicator_id, price_date),
    CONSTRAINT fk_daily_indicators_definitions FOREIGN KEY (indicator_id) REFERENCES public.indicator_definitions (indicator_id) ON DELETE CASCADE,
    CONSTRAINT fk_daily_indicators_tickers FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

-- 3. Create weekly_indicators table
CREATE TABLE public.weekly_indicators (
    weekly_indicator_id bigint GENERATED BY DEFAULT AS IDENTITY,
    indicator_id bigint NOT NULL,
    ticker_id bigint NOT NULL,
    price_date date NOT NULL,
    values jsonb NOT NULL,
    CONSTRAINT weekly_indicators_pkey PRIMARY KEY (weekly_indicator_id),
    CONSTRAINT uk_weekly_indicators UNIQUE (ticker_id, indicator_id, price_date),
    CONSTRAINT fk_weekly_indicators_definitions FOREIGN KEY (indicator_id) REFERENCES public.indicator_definitions (indicator_id) ON DELETE CASCADE,
    CONSTRAINT fk_weekly_indicators_tickers FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

-- 4. Create lookup indexes
CREATE INDEX idx_daily_indicators_lookup
    ON public.daily_indicators USING btree (ticker_id, indicator_id, price_date DESC);

CREATE INDEX idx_weekly_indicators_lookup
    ON public.weekly_indicators USING btree (ticker_id, indicator_id, price_date DESC);
