CREATE TABLE backtest_strategies
(
    backtest_strategy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(255) NOT NULL UNIQUE,
    strategy_type        VARCHAR(100) NOT NULL,
    price_source         VARCHAR(50)
);

CREATE TABLE backtest_strategy_indicators
(
    backtest_strategy_indicator_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_strategy_id           BIGINT       NOT NULL,
    indicator_role                 VARCHAR(100) NOT NULL,
    metric                         VARCHAR(100) NOT NULL,
    transformation                 VARCHAR(20)  NOT NULL,
    period                         INT          NOT NULL,
    CONSTRAINT fk_indicator_strategy FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE
);

-- Add foreign keys to existing backtest tables
ALTER TABLE backtest_results
    ADD COLUMN backtest_strategy_id BIGINT;
ALTER TABLE backtest_results
    ADD CONSTRAINT fk_results_strategy FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE;

ALTER TABLE backtest_equity
    ADD COLUMN backtest_strategy_id BIGINT;
ALTER TABLE backtest_equity
    ADD CONSTRAINT fk_equity_strategy FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE;

ALTER TABLE backtest_signal
    ADD COLUMN backtest_strategy_id BIGINT;
ALTER TABLE backtest_signal
    ADD CONSTRAINT fk_signal_strategy FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE;

ALTER TABLE backtest_trade
    ADD COLUMN backtest_strategy_id BIGINT;
ALTER TABLE backtest_trade
    ADD CONSTRAINT fk_trade_strategy FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE;
