CREATE TYPE sr_current_type AS ENUM ('SUPPORT', 'RESISTANCE');

CREATE TABLE daily_sr (
    id BIGINT NOT NULL,
    ticker_id BIGINT NOT NULL REFERENCES tickers(ticker_id) ON DELETE CASCADE,
    slope NUMERIC NOT NULL,
    intercept NUMERIC NOT NULL,
    current_type sr_current_type NOT NULL,
    break_count INTEGER NOT NULL DEFAULT 0,
    touch_points JSONB NOT NULL DEFAULT '[]'::jsonb,
    importance INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT daily_sr_pkey PRIMARY KEY (id)
);
ALTER TABLE daily_sr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.daily_sr_id_seq);

CREATE INDEX idx_daily_sr_ticker_id ON daily_sr(ticker_id);

CREATE TABLE weekly_sr (
    id BIGINT NOT NULL,
    ticker_id BIGINT NOT NULL REFERENCES tickers(ticker_id) ON DELETE CASCADE,
    slope NUMERIC NOT NULL,
    intercept NUMERIC NOT NULL,
    current_type sr_current_type NOT NULL,
    break_count INTEGER NOT NULL DEFAULT 0,
    touch_points JSONB NOT NULL DEFAULT '[]'::jsonb,
    importance INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT weekly_sr_pkey PRIMARY KEY (id)
);
ALTER TABLE weekly_sr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.weekly_sr_id_seq);

CREATE INDEX idx_weekly_sr_ticker_id ON weekly_sr(ticker_id);
