CREATE TABLE support_resistances (
    id BIGINT NOT NULL,
    ticker_id BIGINT NOT NULL REFERENCES tickers(ticker_id) ON DELETE CASCADE,
    timeframe VARCHAR(20) NOT NULL,
    slope NUMERIC NOT NULL,
    intercept NUMERIC NOT NULL,
    current_type VARCHAR(50) NOT NULL,
    filter_reason VARCHAR(50),
    break_count INTEGER NOT NULL DEFAULT 0,
    touch_points JSONB NOT NULL DEFAULT '[]'::jsonb,
    importance INTEGER NOT NULL DEFAULT 0,
    current_price NUMERIC(18, 4) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT support_resistances_pkey PRIMARY KEY (id)
);

ALTER TABLE support_resistances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.support_resistances_id_seq);
CREATE INDEX idx_support_resistances_ticker_id_timeframe ON support_resistances(ticker_id, timeframe);
