CREATE TABLE renko_bricks
(
    renko_brick_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renko_brick_date DATE           NOT NULL,
    ticker_id        INT            NOT NULL,
    brick_low        NUMERIC(28, 8) NOT NULL,
    brick_high       NUMERIC(28, 8) NOT NULL,
    direction        VARCHAR(10)    NOT NULL,
    trend            INT            NOT NULL,
    zone             INT            NOT NULL
);

ALTER TABLE renko_bricks
    ADD CONSTRAINT fk_renko_data_tickers
        FOREIGN KEY (ticker_id)
            REFERENCES tickers (ticker_id)
            ON DELETE CASCADE;

CREATE INDEX idx_renko_data_ticker ON renko_bricks (ticker_id);
