-- ==========================================
-- 20. CREATE CANDLESTICK PATTERN TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.daily_candlestick_patterns (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    price_date DATE NOT NULL,
    pattern_name VARCHAR(50) NOT NULL,
    sentiment VARCHAR(10) NOT NULL,
    CONSTRAINT uk_daily_candlestick_patterns UNIQUE (ticker_id, price_date, pattern_name),
    CONSTRAINT fk_daily_patterns_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.weekly_candlestick_patterns (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    price_date DATE NOT NULL,
    pattern_name VARCHAR(50) NOT NULL,
    sentiment VARCHAR(10) NOT NULL,
    CONSTRAINT uk_weekly_candlestick_patterns UNIQUE (ticker_id, price_date, pattern_name),
    CONSTRAINT fk_weekly_patterns_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE INDEX idx_daily_patterns_lookup ON public.daily_candlestick_patterns (ticker_id, price_date DESC);
CREATE INDEX idx_weekly_patterns_lookup ON public.weekly_candlestick_patterns (ticker_id, price_date DESC);
