CREATE TABLE weekly_candle_data
(
    weekly_candle_data_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candle_date           DATE                 NOT NULL,
    ticker_id             BIGINT               NOT NULL,
    price_open            NUMERIC(38, 2)       NOT NULL,
    price_high            NUMERIC(38, 2)       NOT NULL,
    price_low             NUMERIC(38, 2)       NOT NULL,
    price_close           NUMERIC(38, 2)       NOT NULL,
    volume                NUMERIC(38, 2)       NOT NULL,
    is_final              BOOLEAN              NOT NULL,
    CONSTRAINT fk_weekly_candle_data_tickers FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT uk_weekly_market_data UNIQUE (ticker_id, candle_date)
);

CREATE INDEX idx_weekly_candle_data_ticker ON weekly_candle_data(ticker_id);
