CREATE TABLE backtest_strategies
(
    backtest_strategy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(255)         NOT NULL UNIQUE,
    strategy_type        VARCHAR(100)         NOT NULL,
    is_active            BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE backtest_indicators
(
    backtest_indicator_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_strategy_id  BIGINT       NOT NULL,
    metric                VARCHAR(100) NOT NULL,
    transformation        VARCHAR(50)  NOT NULL,
    period                INTEGER      NOT NULL,
    indicator_role        VARCHAR(50)  NOT NULL,
    CONSTRAINT fk_backtest_indicators_strategy FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE
);

CREATE TABLE backtest_equities
(
    backtest_equities_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id            INTEGER        NOT NULL,
    backtest_strategy_id BIGINT,
    equity_date          DATE           NOT NULL,
    equity               NUMERIC(38, 2) NOT NULL,
    position             VARCHAR(10)    NOT NULL,
    price_close          NUMERIC(38, 2) NOT NULL,
    CONSTRAINT fk_backtest_equities_tickers FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT fk_backtest_equities_strategies FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE
);

CREATE TABLE backtest_signals
(
    backtest_signals_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id            INTEGER      NOT NULL,
    backtest_strategy_id BIGINT,
    signal_date          DATE         NOT NULL,
    execute_date         DATE,
    action               VARCHAR(20)  NOT NULL,
    signal_data          TEXT,
    strategy_state       TEXT,
    CONSTRAINT fk_backtest_signals_tickers FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT fk_backtest_signals_strategies FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE
);

CREATE TABLE backtest_trades
(
    backtest_trades_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id            INTEGER        NOT NULL,
    backtest_strategy_id BIGINT,
    side                 VARCHAR(10)    NOT NULL,
    entry_date           DATE           NOT NULL,
    entry_price          NUMERIC(38, 2) NOT NULL,
    exit_date            DATE,
    exit_price           NUMERIC(38, 2),
    quantity             NUMERIC(38, 4) NOT NULL,
    pnl                  NUMERIC(38, 2),
    pnl_pct              NUMERIC(38, 2),
    holding_bars         INTEGER        NOT NULL,
    CONSTRAINT fk_backtest_trades_tickers FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT fk_backtest_trades_strategies FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE
);

CREATE TABLE backtest_results
(
    backtest_results_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id            INTEGER        NOT NULL,
    backtest_strategy_id BIGINT,
    initial_equity       NUMERIC(38, 2) NOT NULL,
    final_equity         NUMERIC(38, 2) NOT NULL,
    start_date           DATE           NOT NULL,
    end_date             DATE           NOT NULL,
    years                NUMERIC(38, 4) NOT NULL,
    cagr                 NUMERIC(38, 4) NOT NULL,
    win_rate             NUMERIC(38, 2) NOT NULL,
    total_return_pct     NUMERIC(38, 2) NOT NULL,
    max_drawdown_pct     NUMERIC(38, 2) NOT NULL,
    sharpe_ratio         NUMERIC(38, 4) NOT NULL,
    total_trades         INTEGER        NOT NULL,
    avg_win              NUMERIC(38, 2) NOT NULL,
    avg_loss             NUMERIC(38, 2) NOT NULL,
    profit_factor        NUMERIC(38, 2) NOT NULL,
    expectancy           NUMERIC(38, 2) NOT NULL,
    CONSTRAINT fk_backtest_results_tickers FOREIGN KEY (ticker_id) REFERENCES tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT fk_backtest_results_strategies FOREIGN KEY (backtest_strategy_id) REFERENCES backtest_strategies (backtest_strategy_id) ON DELETE CASCADE
);
