-- ==========================================
-- 25. CREATE CHART PATTERN TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.daily_chart_patterns (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    pattern_type VARCHAR(50) NOT NULL,
    sentiment VARCHAR(25) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    breakout_date DATE,
    neckline_slope NUMERIC(18, 4),
    neckline_price NUMERIC(18, 4),
    invalidation_price NUMERIC(18, 4),
    pivot_points JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_chart_patterns UNIQUE (ticker_id, pattern_type, start_date),
    CONSTRAINT fk_daily_chart_patterns_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.weekly_chart_patterns (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    pattern_type VARCHAR(50) NOT NULL,
    sentiment VARCHAR(25) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    breakout_date DATE,
    neckline_slope NUMERIC(18, 4),
    neckline_price NUMERIC(18, 4),
    invalidation_price NUMERIC(18, 4),
    pivot_points JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_weekly_chart_patterns UNIQUE (ticker_id, pattern_type, start_date),
    CONSTRAINT fk_weekly_chart_patterns_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_daily_chart_patterns_lookup ON public.daily_chart_patterns (ticker_id, end_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_chart_patterns_status ON public.daily_chart_patterns (ticker_id, status);

CREATE INDEX IF NOT EXISTS idx_weekly_chart_patterns_lookup ON public.weekly_chart_patterns (ticker_id, end_date DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_chart_patterns_status ON public.weekly_chart_patterns (ticker_id, status);
