-- ==========================================
-- 27. IMPROVE DB SCHEMA: UNIFORM PK NAMING, CASCADE DELETE, COLUMN REORDERING
-- ==========================================

-- 1. Rename PK on indicator_definitions and FK on daily/weekly_indicators
ALTER TABLE public.indicator_definitions RENAME COLUMN indicator_id TO indicator_definition_id;
ALTER TABLE public.daily_indicators RENAME COLUMN indicator_id TO indicator_definition_id;
ALTER TABLE public.weekly_indicators RENAME COLUMN indicator_id TO indicator_definition_id;

-- 2. Truncate and rename PK on candlestick pattern tables
TRUNCATE TABLE public.daily_candlestick_patterns;
TRUNCATE TABLE public.weekly_candlestick_patterns;
ALTER TABLE public.daily_candlestick_patterns RENAME COLUMN id TO daily_candlestick_pattern_id;
ALTER TABLE public.weekly_candlestick_patterns RENAME COLUMN id TO weekly_candlestick_pattern_id;

-- 3. Re-order columns and rename PK for daily_chart_patterns and weekly_chart_patterns
DROP TABLE IF EXISTS public.daily_chart_patterns CASCADE;
CREATE TABLE IF NOT EXISTS public.daily_chart_patterns (
    daily_chart_pattern_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    pattern_type VARCHAR(50) NOT NULL,
    sentiment VARCHAR(25) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    breakout_date DATE,
    neckline_slope NUMERIC(18, 4),
    neckline_price NUMERIC(18, 4),
    target_price NUMERIC(18, 4),
    stop_loss_price NUMERIC(18, 4),
    invalidation_price NUMERIC(18, 4),
    pivot_points JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_chart_patterns UNIQUE (ticker_id, pattern_type, start_date),
    CONSTRAINT fk_daily_chart_patterns_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_daily_chart_patterns_lookup ON public.daily_chart_patterns (ticker_id, end_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_chart_patterns_status ON public.daily_chart_patterns (ticker_id, status);

DROP TABLE IF EXISTS public.weekly_chart_patterns CASCADE;
CREATE TABLE IF NOT EXISTS public.weekly_chart_patterns (
    weekly_chart_pattern_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    pattern_type VARCHAR(50) NOT NULL,
    sentiment VARCHAR(25) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    breakout_date DATE,
    neckline_slope NUMERIC(18, 4),
    neckline_price NUMERIC(18, 4),
    target_price NUMERIC(18, 4),
    stop_loss_price NUMERIC(18, 4),
    invalidation_price NUMERIC(18, 4),
    pivot_points JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_weekly_chart_patterns UNIQUE (ticker_id, pattern_type, start_date),
    CONSTRAINT fk_weekly_chart_patterns_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_weekly_chart_patterns_lookup ON public.weekly_chart_patterns (ticker_id, end_date DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_chart_patterns_status ON public.weekly_chart_patterns (ticker_id, status);

-- 4. Re-order columns and rename PK for daily_support_resistances and weekly_support_resistances
DROP TABLE IF EXISTS public.daily_support_resistances CASCADE;
CREATE TABLE IF NOT EXISTS public.daily_support_resistances (
    daily_support_resistance_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    price_date DATE NOT NULL,
    zone_bottom NUMERIC(18, 4) NOT NULL,
    zone_top NUMERIC(18, 4) NOT NULL,
    zone_midpoint NUMERIC(18, 4) NOT NULL,
    touch_count INTEGER NOT NULL,
    level_type VARCHAR(20) NOT NULL,
    first_touch_date DATE,
    last_touch_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_support_resistances UNIQUE (ticker_id, price_date, zone_bottom, zone_top),
    CONSTRAINT fk_daily_support_resistances_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dsr_ticker_date ON public.daily_support_resistances (ticker_id, price_date);

DROP TABLE IF EXISTS public.weekly_support_resistances CASCADE;
CREATE TABLE IF NOT EXISTS public.weekly_support_resistances (
    weekly_support_resistance_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    price_date DATE NOT NULL,
    zone_bottom NUMERIC(18, 4) NOT NULL,
    zone_top NUMERIC(18, 4) NOT NULL,
    zone_midpoint NUMERIC(18, 4) NOT NULL,
    touch_count INTEGER NOT NULL,
    level_type VARCHAR(20) NOT NULL,
    first_touch_date DATE,
    last_touch_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_weekly_support_resistances UNIQUE (ticker_id, price_date, zone_bottom, zone_top),
    CONSTRAINT fk_weekly_support_resistances_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_wsr_ticker_date ON public.weekly_support_resistances (ticker_id, price_date);
