-- ==========================================
-- 30. ADD DATA_PROVIDER AND INSTRUMENT_TOKEN TO TICKERS, CREATE INTRADAY_PRICES TABLE
-- ==========================================

ALTER TABLE public.tickers
ADD COLUMN IF NOT EXISTS data_provider VARCHAR(50) NOT NULL DEFAULT 'YAHOO_FINANCE';

ALTER TABLE public.tickers
ADD COLUMN IF NOT EXISTS instrument_token VARCHAR(50);

CREATE TABLE IF NOT EXISTS public.intraday_prices (
    intraday_price_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id INT8 NOT NULL,
    timeframe VARCHAR(20) NOT NULL,
    price_time TIMESTAMP WITH TIME ZONE NOT NULL,
    price_open NUMERIC(18, 4) NOT NULL,
    price_high NUMERIC(18, 4) NOT NULL,
    price_low NUMERIC(18, 4) NOT NULL,
    price_close NUMERIC(18, 4) NOT NULL,
    volume NUMERIC(18, 4) NOT NULL DEFAULT 0,
    CONSTRAINT fk_intraday_prices_ticker FOREIGN KEY (ticker_id) REFERENCES public.tickers (ticker_id) ON DELETE CASCADE,
    CONSTRAINT uk_intraday_prices UNIQUE (ticker_id, timeframe, price_time)
);

CREATE INDEX IF NOT EXISTS idx_intraday_prices_lookup ON public.intraday_prices (ticker_id, timeframe, price_time DESC);
