package com.alphaflow.persistence.enums;

public enum SRFilterReason {
  HZ_BREAKS_GT_2,
  HZ_BREAKS_GT_4,
  HZ_TOUCHES_LT_2,
  HZ_TOUCHES_LT_3,
  HZ_PROXIMITY_1_PCT,
  HZ_CIRCUIT_BREAKER_20_PCT,

  ANG_BREAKS_GT_2,
  ANG_BREAKS_GT_4,
  ANG_TOUCHES_LT_4,
  ANG_PROXIMITY_1_PCT,
  ANG_CIRCUIT_BREAKER_35_PCT
}
