spring.application.name=TechnicalAnalysisApplication

binance.sync.tickers=BTCUSDT,ETHUSDT
binance.sync.start-date=2023-01-01
binance.sync.output-dir=./binance-data

app.tickers.BTCUSDT=2017-08-17
app.tickers.ETHUSDT=2021-06-15


# Expose all actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
