spring.application.name=TechnicalAnalysisApplication

# Crypto List over $10B Market Cap (As of 28-Aug-2025), excluding stable coins and wrapped tokens
# Store-of-Value / Payments
app.binance.tickers.BTCUSDT=2017-08-17
app.binance.tickers.XRPUSDT=2018-05-04
app.binance.tickers.XLMUSDT=2018-05-31
app.binance.tickers.TRXUSDT=2018-06-11
app.binance.tickers.DOGEUSDT=2019-07-05
# Smart-Contract Platforms (Layer-1 chains)
app.binance.tickers.ETHUSDT=2017-08-17
app.binance.tickers.BNBUSDT=2017-11-06
app.binance.tickers.ADAUSDT=2018-04-17
app.binance.tickers.HBARUSDT=2019-09-29
app.binance.tickers.SOLUSDT=2020-08-11
app.binance.tickers.AVAXUSDT=2020-09-22
app.binance.tickers.SUIUSDT=2023-05-03
# Infrastructure / Middleware
app.binance.tickers.LINKUSDT=2019-01-16
# Speculative / Emerging
app.binance.tickers.HYPEUSDT=

# Directory where files will be downloaded
app.download-dir=/Volumes/Prem/Binance

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
